# frozen_string_literal: true

# Generated by provider-integrator 0.1.0 from "Kassira Merchant API" 2.4 (OpenAPI 3.0.3).
# Contract: Provider::BaseService (see INTEGRATION.md; base_contract.rb is a stub for local runs).
# Do not edit by hand: re-run the generator and pin corrections in overrides.yml.
# "Evidence:" comments cite the spec; "TODO(confidence ...)" marks what needs confirmation.

require 'openssl'
require 'uri'

class Provider
  class KassiraService < BaseService
    # Unknown by default.
    BASE_URL = ENV.fetch('KASSIRA_BASE_URL', 'https://api.kassira.example/merchant/v2')

    # Sent in the request body as callback_url; configure per environment.
    CALLBACK_URL = ENV.fetch('KASSIRA_CALLBACK_URL', nil)

    # Payout methods accepted as request_method (enum of payment_type); the first is the default.
    REQUEST_METHODS = %w[card account phone].freeze

    # minimum of sum: 10000 in minor units of the provider = 100 in major units of operation.amount.
    MIN_AMOUNT = 100

    # Canonical requisite names each payout method needs (required in the schema, or required when the
    # method matches - see INTEGRATION.md).
    REQUIRED_REQUISITES = {
      'card'    => %w[card_number],
      'account' => %w[account_number bank_code],
      'phone'   => %w[phone]
    }.freeze

    # POST /payment/create (post_payment_create).
    def create_request(operation, request_method = 'card')
      payload =
        case request_method
        when 'card' then build_card_payload(operation)
        when 'account' then build_account_payload(operation)
        when 'phone' then build_phone_payload(operation)
        end
      return failure(:unprocessable_entity, 'unsupported_request_method') if payload.nil?

      headers = auth_headers.merge(idempotency_headers(operation))
      response = client.post("#{BASE_URL}/payment/create", form: payload, headers: headers)
      parse_create_response(operation, response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # GET /payment/status/{payment_id} (get_payment_status_payment_id).
    def fetch_status(operation)
      response = client.get("#{BASE_URL}/payment/status/#{operation.provider_operation_id}", headers: auth_headers)
      parse_status_response(operation, response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # POST /callback/payment (post_callback_payment); source: path_heuristic.
    # payload is the parsed JSON body, or { 'body' => body, 'headers' => headers, 'raw_body' => raw body }
    # (INTEGRATION.md, Webhook).
    def process_callback(payload)
      verify_signature!(payload) # MD5 from X-Sign
      body = callback_body(payload)
      # Events without a canonical status (W203), answered as unknown_event: PAYMENT_IN_WORK
      case body['notification_type']
      when 'PAYMENT_REGISTERED' then success(status: 'in_progress', response: body)
      when 'PAYMENT_PAID' then approve_operation(body['payment_id'])
      when 'PAYMENT_REFUSED', 'PAYMENT_RETURNED', 'PAYMENT_EXPIRED' then reject_operation(body['payment_id'],
                                                                                          body['fault_code'])
      else failure(:unprocessable_entity, 'unknown_event')
      end
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'invalid_signature')
    end

    # Pre-checks before create_request; super runs the platform checks first.
    def check_conditions(operation, request_method)
      base_result = super
      return base_result if base_result.failed?

      unless REQUEST_METHODS.include?(request_method)
        return failure(:unprocessable_entity, 'unsupported_request_method')
      end
      # Evidence: description: копейках; minimum: 10000
      return failure(:unprocessable_entity, 'amount_too_low') if operation.amount < MIN_AMOUNT

      missing = missing_requisites(operation, request_method)
      return failure(:unprocessable_entity, 'missing_requisite') unless missing.empty?

      success
    end

    # Outside the BaseService contract (kind cancel): POST /payment/cancel/{payment_id}
    # (post_payment_cancel_payment_id).
    # Отмена платёжного поручения
    def cancel_request(operation)
      payload = build_cancel_request_payload(operation)
      url = "#{BASE_URL}/payment/cancel/#{operation.provider_operation_id}"
      response = client.post(url, form: payload, headers: auth_headers)
      parse_cancel_request_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # Outside the BaseService contract (kind unknown): POST /requisites/check (post_requisites_check).
    # Проверка реквизитов получателя
    # TODO(confidence 0.0): operation kind unknown with confidence 0.0
    def post_requisites_check(operation, request_method)
      payload = build_post_requisites_check_payload(operation, request_method)
      url = "#{BASE_URL}/requisites/check"
      response = client.post(url, form: payload, headers: auth_headers)
      parse_post_requisites_check_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # Outside the BaseService contract (kind balance): GET /merchant/balance (get_merchant_balance).
    # Баланс договора
    def fetch_balance
      url = "#{BASE_URL}/merchant/balance"
      response = client.get(url, headers: auth_headers)
      parse_fetch_balance_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # Outside the BaseService contract (kind list): GET /dictionary/banks (get_dictionary_banks).
    # Справочник банков получателей
    # TODO(confidence 0.5): operation kind list with confidence 0.5
    def list_requests(params = {})
      url = "#{BASE_URL}/dictionary/banks"
      url = "#{url}?#{URI.encode_www_form(params)}" unless params.empty?
      response = client.get(url, headers: auth_headers)
      parse_list_requests_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    private

    # Body of POST /payment/create for request_method 'card'.
    def build_card_payload(operation)
      {
        merchant_id: credentials[:merchant_id],
        # TODO(confidence 0.0): required field contract_num has no platform source (W403)
        contract_num: nil,
        order_id: operation.id,
        # Evidence: description: копейках; minimum: 10000
        sum: amount_in_minor_units(operation.amount),
        cur: 'RUB',
        payment_type: 'card',
        # TODO(confidence 0.6): required when payment_type = card (description: Обязателен, если payment_type
        # = card)
        pan: operation.payout_requisite.dig('card', 'card_number'),
        payee_name: operation.payout_requisite.dig('card', 'name'),
        callback_url: CALLBACK_URL
      }.compact
    end

    # Body of POST /payment/create for request_method 'account'.
    def build_account_payload(operation)
      {
        merchant_id: credentials[:merchant_id],
        # TODO(confidence 0.0): required field contract_num has no platform source (W403)
        contract_num: nil,
        order_id: operation.id,
        # Evidence: description: копейках; minimum: 10000
        sum: amount_in_minor_units(operation.amount),
        cur: 'RUB',
        payment_type: 'account',
        # TODO(confidence 0.6): required when payment_type = account (description: Обязателен, если
        # payment_type = account)
        account_no: operation.payout_requisite.dig('account', 'account_number'),
        # TODO(confidence 0.6): required when payment_type = account (description: Обязателен, если
        # payment_type = account)
        bik: operation.payout_requisite.dig('account', 'bank_code'),
        payee_name: operation.payout_requisite.dig('account', 'name'),
        callback_url: CALLBACK_URL
      }.compact
    end

    # Body of POST /payment/create for request_method 'phone'.
    def build_phone_payload(operation)
      {
        merchant_id: credentials[:merchant_id],
        # TODO(confidence 0.0): required field contract_num has no platform source (W403)
        contract_num: nil,
        order_id: operation.id,
        # Evidence: description: копейках; minimum: 10000
        sum: amount_in_minor_units(operation.amount),
        cur: 'RUB',
        payment_type: 'phone',
        # TODO(confidence 0.6): required when payment_type = phone (description: Обязателен, если payment_type
        # = phone)
        phone_number: operation.payout_requisite.dig('phone', 'phone'),
        payee_name: operation.payout_requisite.dig('phone', 'name'),
        callback_url: CALLBACK_URL
      }.compact
    end

    # Success statuses 200, 409; everything else goes through ERROR_MAP.
    def parse_create_response(operation, response)
      body = response.body || {}
      case response.status
      # 409: duplicate by idempotency key - the provider returns the original result, treated as success.
      when 200, 409 then success(provider_operation_id: body['payment_id'], status: map_status(body['state']),
                                 response: body)
      else provider_error(response)
      end
    end

    def parse_status_response(operation, response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(status: map_status(body['state']), response: body)
    end

    # The parsed notification: payload['body'] under the platform envelope, else the payload itself.
    def callback_body(payload)
      payload['body'] || payload
    end

    # MD5 over the payload values concatenated, hex, compared in constant time.
    # Evidence: parameter X-Sign (header): Контрольная подпись уведомления: MD5-хеш от склеенных значений
    # полей payment_id,
    # TODO(confidence 0.4): how the secret is mixed into the digest is not in the spec; message + secret
    # assumed
    def verify_signature!(payload)
      signature = payload.dig('headers', 'X-Sign').to_s
      message = callback_body(payload).except('X-Sign').sort.map { |_, value| value.to_s }.join
      expected = OpenSSL::Digest.hexdigest('MD5', "#{message}#{credentials[:callback_secret]}")
      return if !signature.empty? && secure_compare(expected, signature)

      raise Provider::UnauthorizedError, 'invalid_signature'
    end

    def secure_compare(left, right)
      left.bytesize == right.bytesize && OpenSSL.fixed_length_secure_compare(left, right)
    end

    # Canonical requisite names the payout method needs (REQUIRED_REQUISITES) that are missing from
    # operation.payout_requisite[request_method].
    def missing_requisites(operation, request_method)
      requisite = operation.payout_requisite.to_h[request_method] || {}
      REQUIRED_REQUISITES.fetch(request_method, []).reject { |field| requisite[field] }
    end

    # Body of POST /payment/cancel/{payment_id}.
    def build_cancel_request_payload(operation, request_method = nil)
      {}.compact
    end

    def parse_cancel_request_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(status: map_status(body['state']), response: body)
    end

    # Body of POST /requisites/check.
    def build_post_requisites_check_payload(operation, request_method = nil)
      {
        payment_type: request_method,
        pan: operation.payout_requisite.dig(request_method, 'card_number'),
        account_no: operation.payout_requisite.dig(request_method, 'account_number'),
        bik: operation.payout_requisite.dig(request_method, 'bank_code')
      }.compact
    end

    def parse_post_requisites_check_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(response: body)
    end

    def parse_fetch_balance_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(response: body)
    end

    def parse_list_requests_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(response: body)
    end

    # MerchantToken: api_key in header X-Merchant-Token. Evidence: securitySchemes.MerchantToken: apiKey
    # in header X-Merchant-Token; security: MerchantToken used by 6 of 7 operations
    def auth_headers
      { 'X-Merchant-Token' => credentials[:api_key] }
    end

    # X-Request-Id: operation.id is the stable key of the request; the provider answers a repeat with the
    # original result.
    def idempotency_headers(operation)
      { 'X-Request-Id' => operation.id.to_s }
    end

    # Provider status -> Space Payments status (STATUS_MAP); unknown values stay in_progress until the
    # next notification.
    def map_status(value)
      STATUS_MAP.fetch(value.to_s, 'in_progress')
    end

    # Error response -> failure through ERROR_MAP (HTTP status -> canonical code).
    def provider_error(response)
      body = response.body || {}
      details = { provider_code: error_code(body), retry_after: retry_after_seconds(response) }.compact
      case ERROR_MAP.fetch(response.status) { response.status >= 500 ? 'internal_error' : 'validation_error' }
      when 'invalid_credentials' then failure(:unauthorized, 'provider.invalid_credentials', **details)
      when 'insufficient_balance' then failure(:provider_error, 'provider.insufficient_balance', **details)
      when 'rate_limit' then failure(:too_many_requests, 'provider.rate_limit', **details)
      when 'internal_error' then failure(:provider_error, 'provider.internal_error', **details)
      when 'not_found' then failure(:provider_error, 'provider.not_found', **details)
      when 'conflict' then failure(:unprocessable_entity, 'provider.conflict', **details)
      else failure(:unprocessable_entity, 'provider.validation_error', **details)
      end
    end

    # Retry-After of a rate-limited response in seconds (header); nil when the provider sent none.
    def retry_after_seconds(response)
      header = response.headers.to_h.find { |name, _| name.to_s.casecmp?('Retry-After') }&.last
      header&.to_i
    end

    # Provider error code of an error response (fault_code in the spec).
    def error_code(body)
      body['fault_code']&.to_s
    end

    # operation.amount is in major units; the provider expects minor units (x 100).
    # round (not to_i) keeps 10.15 * 100 from truncating to 1014 with Float amounts.
    def amount_in_minor_units(amount)
      (amount * 100).round
    end

    # Provider status -> Space Payments status (statuses.yml); evidence per status in INTEGRATION.md.
    STATUS_MAP = {
      'REGISTERED' => 'in_progress',
      # TODO(confidence 0.3): default: in_progress
      'IN_WORK'    => 'in_progress',
      'PAID'       => 'approved',
      'RETURNED'   => 'rejected',
      'REFUSED'    => 'rejected',
      'EXPIRED'    => 'rejected'
    }.freeze

    # HTTP status -> canonical error code (Space Payments); provider codes and evidence in INTEGRATION.md.
    ERROR_MAP = {
      400 => 'validation_error',
      401 => 'invalid_credentials',
      402 => 'insufficient_balance',
      404 => 'not_found',
      409 => 'conflict',
      429 => 'rate_limit',
      500 => 'internal_error'
    }.freeze

    # HTTP status -> what the platform should do (canonical_contract.yml -> actions).
    ERROR_ACTIONS = {
      400 => 'terminal_reject',
      401 => 'fatal_block_provider',
      402 => 'retry_later',
      404 => 'unknown_state',
      409 => 'conflict',
      429 => 'retry_with_backoff',
      500 => 'retry_alert_ops'
    }.freeze
  end
end
