# frozen_string_literal: true

# Generated by provider-integrator 0.1.0: RSpec for Provider::KassiraService over fixtures.json
# through WebMock (no network).
# Run from this directory: rspec kassira_service_spec.rb (gems: rspec, webmock).
# base_contract.rb (Provider::BaseService, Provider::HttpClient) is a stub for local runs
# (docs/ASSUMPTIONS.md).

require 'json'
require 'openssl'
require 'rspec'
require 'uri'
require 'webmock/rspec'
require_relative 'base_contract'
require_relative 'kassira_service'

RSpec.describe Provider::KassiraService do
  let(:fixtures) { JSON.parse(File.read(File.join(__dir__, 'fixtures.json'))) }
  let(:credentials) do
    { api_key: 'test-api_key', callback_secret: 'test-callback_secret', merchant_id: 'string' }
  end
  let(:service) { described_class.new(client: Provider::HttpClient.new, credentials: credentials) }
  let(:requests) { [] }
  # The platform operation built from fixtures.json (the create request and its success response).
  let(:operation) do
    Provider::Operation.new(
      id: 'string',
      amount: 100,
      currency: 'RUB',
      provider_operation_id: 'string',
      payout_requisite: { 'card' => { 'card_number' => 'test-card_number', 'name' => 'test-name' } }
    )
  end

  # An example of fixtures.json without the generator markers (_synthetic, _synthetic_fields).
  def fixture(*keys)
    fixtures.dig(*keys).reject { |key, _| key.start_with?('_') }
  end

  # Stubs one provider response and records every request the service sends to url.
  def stub_provider(verb, url, status, body, headers: {})
    stub_request(verb, url).to_return do |request|
      requests << request
      { status: status, body: JSON.generate(body), headers: { 'Content-Type' => 'application/json' }.merge(headers) }
    end
  end

  # The body of the last request the service sent, as the provider reads it.
  def sent_body
    URI.decode_www_form(requests.last.body).to_h
  end

  # A copy of the operation with some members replaced.
  def operation_with(**changes)
    Provider::Operation.new(**operation.to_h, **changes)
  end

  # Signs a notification body the way verify_signature! checks it (MD5, hex).
  def signature_for(body)
    message = body.except('X-Sign').sort.map { |_, value| value.to_s }.join
    OpenSSL::Digest.hexdigest('MD5', "#{message}#{credentials[:callback_secret]}")
  end

  # The payload process_callback receives for a signed notification.
  def signed_payload(body)
    {
      'body'     => body,
      'raw_body' => JSON.generate(body),
      'headers'  => { 'X-Sign' => signature_for(body) }
    }
  end

  describe '#create_request' do
    let(:url) { "#{described_class::BASE_URL}/payment/create" }
    let(:request_headers) { { 'X-Merchant-Token' => 'test-api_key', 'X-Request-Id' => 'string' } }

    it 'POSTs the create request of fixtures.json with the auth headers' do
      stub_provider(:post, url, 200, fixture('create_request', 'response_200'))

      service.create_request(operation, 'card')

      expect(a_request(:post, url).with(headers: request_headers)).to have_been_made.once
      expect(sent_body).to include(
        'merchant_id'  => 'string',
        'order_id'     => 'string',
        'sum'          => '10000',
        'cur'          => 'RUB',
        'payment_type' => 'card',
        'pan'          => 'test-card_number',
        'payee_name'   => 'test-name'
      )
    end

    it 'returns success with the provider id and the mapped status of response_200' do
      stub_provider(:post, url, 200, fixture('create_request', 'response_200'))

      result = service.create_request(operation, 'card')

      expect(result).to be_success
      expect(result.provider_operation_id).to eq('string')
      expect(result.status).to eq('in_progress')
    end

    it 'treats HTTP 409 (idempotent duplicate) as success' do
      stub_provider(:post, url, 409, fixture('create_request', 'response_409'))

      result = service.create_request(operation, 'card')

      expect(result).to be_success
      expect(result.provider_operation_id).to eq('string')
      expect(result.status).to eq('in_progress')
    end

    it 'maps HTTP 400 to failure(:unprocessable_entity, provider.validation_error)' do
      stub_provider(:post, url, 400, fixture('create_request', 'response_400'))

      result = service.create_request(operation, 'card')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'provider.validation_error'])
      expect(result.details[:provider_code]).to eq('INVALID_PARAM')
    end

    it 'maps HTTP 401 to failure(:unauthorized, provider.invalid_credentials)' do
      stub_provider(:post, url, 401, fixture('create_request', 'response_401'))

      result = service.create_request(operation, 'card')

      expect([result.error, result.code]).to eq([:unauthorized, 'provider.invalid_credentials'])
      expect(result.details[:provider_code]).to eq('SIGN_ERROR')
    end

    it 'maps HTTP 402 to failure(:provider_error, provider.insufficient_balance)' do
      stub_provider(:post, url, 402, fixture('create_request', 'response_402'))

      result = service.create_request(operation, 'card')

      expect([result.error, result.code]).to eq([:provider_error, 'provider.insufficient_balance'])
      expect(result.details[:provider_code]).to eq('NOT_ENOUGH_FUNDS')
    end

    it 'maps HTTP 429 to failure(:too_many_requests, provider.rate_limit) with Retry-After' do
      stub_provider(:post, url, 429, fixture('create_request', 'response_429'), headers: { 'Retry-After' => '60' })

      result = service.create_request(operation, 'card')

      expect([result.error, result.code]).to eq([:too_many_requests, 'provider.rate_limit'])
      expect(result.details[:provider_code]).to eq('REQUEST_LIMIT')
      expect(result.details[:retry_after]).to eq(60)
    end

    it 'maps HTTP 500 to failure(:provider_error, provider.internal_error)' do
      stub_provider(:post, url, 500, fixture('create_request', 'response_500'))

      result = service.create_request(operation, 'card')

      expect([result.error, result.code]).to eq([:provider_error, 'provider.internal_error'])
      expect(result.details[:provider_code]).to eq('INTERNAL_FAILURE')
    end

    it 'refuses an unknown request_method without calling the provider' do
      result = service.create_request(operation, 'unsupported')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'unsupported_request_method'])
      expect(WebMock).not_to have_requested(:any, /./)
    end
  end

  describe '#fetch_status' do
    let(:url) { "#{described_class::BASE_URL}/payment/status/#{operation.provider_operation_id}" }

    it 'GETs the operation with the auth headers and maps the status of response_200' do
      stub_provider(:get, url, 200, fixture('fetch_status', 'response_200'))

      result = service.fetch_status(operation)

      expect(a_request(:get, url).with(headers: { 'X-Merchant-Token' => 'test-api_key' })).to have_been_made.once
      expect(result).to be_success
      expect(result.status).to eq('in_progress')
    end

    it 'maps HTTP 401 to failure(:unauthorized, provider.invalid_credentials)' do
      stub_provider(:get, url, 401, fixture('fetch_status', 'response_401'))

      result = service.fetch_status(operation)

      expect([result.error, result.code]).to eq([:unauthorized, 'provider.invalid_credentials'])
      expect(result.details[:provider_code]).to eq('SIGN_ERROR')
    end

    it 'maps HTTP 404 to failure(:provider_error, provider.not_found)' do
      stub_provider(:get, url, 404, fixture('fetch_status', 'response_404'))

      result = service.fetch_status(operation)

      expect([result.error, result.code]).to eq([:provider_error, 'provider.not_found'])
      expect(result.details[:provider_code]).to eq('DOC_NOT_FOUND')
    end

    it 'maps HTTP 500 to failure(:provider_error, provider.internal_error)' do
      stub_provider(:get, url, 500, fixture('fetch_status', 'response_500'))

      result = service.fetch_status(operation)

      expect([result.error, result.code]).to eq([:provider_error, 'provider.internal_error'])
      expect(result.details[:provider_code]).to eq('INTERNAL_FAILURE')
    end
  end

  describe '#process_callback' do
    it 'reports in_progress for the callback_registered fixture (notification_type PAYMENT_REGISTERED)' do
      result = service.process_callback(signed_payload(fixture('callback_registered', 'payload')))

      expect(result).to be_success
      expect(result.status).to eq('in_progress')
    end

    it 'approves the operation for the callback fixture (notification_type PAYMENT_PAID)' do
      result = service.process_callback(signed_payload(fixture('callback', 'payload')))

      expect(result).to be_success
      expect(result.status).to eq('approved')
      expect(result.provider_operation_id).to eq('string')
    end

    it 'rejects the operation for the callback_failed fixture (notification_type PAYMENT_REFUSED)' do
      result = service.process_callback(signed_payload(fixture('callback_failed', 'payload')))

      expect(result).to be_success
      expect(result.status).to eq('rejected')
      expect(result.provider_operation_id).to eq('string')
      expect(result.details[:error_code]).to eq('string')
    end

    it 'rejects the operation for the callback_returned fixture (notification_type PAYMENT_RETURNED)' do
      result = service.process_callback(signed_payload(fixture('callback_returned', 'payload')))

      expect(result).to be_success
      expect(result.status).to eq('rejected')
      expect(result.provider_operation_id).to eq('string')
      expect(result.details[:error_code]).to eq('string')
    end

    it 'rejects the operation for the callback_expired fixture (notification_type PAYMENT_EXPIRED)' do
      result = service.process_callback(signed_payload(fixture('callback_expired', 'payload')))

      expect(result).to be_success
      expect(result.status).to eq('rejected')
      expect(result.provider_operation_id).to eq('string')
      expect(result.details[:error_code]).to eq('string')
    end

    it 'refuses a payload whose signature does not verify' do
      payload = signed_payload(fixture('callback_registered', 'payload'))
      payload['headers']['X-Sign'] = 'invalid'

      result = service.process_callback(payload)

      expect([result.error, result.code]).to eq([:unauthorized, 'invalid_signature'])
    end
  end

  describe '#check_conditions' do
    it 'accepts the operation built from fixtures.json' do
      expect(service.check_conditions(operation, 'card')).to be_success
    end

    it 'refuses an amount below MIN_AMOUNT' do
      result = service.check_conditions(operation_with(amount: described_class::MIN_AMOUNT - 1), 'card')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'amount_too_low'])
    end

    it 'refuses an operation without the requisites of REQUIRED_REQUISITES' do
      result = service.check_conditions(operation_with(payout_requisite: {}), 'card')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'missing_requisite'])
    end

    it 'refuses a request_method outside REQUEST_METHODS' do
      result = service.check_conditions(operation, 'unsupported')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'unsupported_request_method'])
    end
  end
end
