# frozen_string_literal: true

module ProviderIntegrator
  module TemplateData
    # Everything service.rb.erb prints, computed once in dependency order: methods first (they
    # decide which helpers, ENV constants and requires exist), then constants. The template only
    # walks the lists; every naming decision happens here or in the pieces this class assembles.
    class Service
      attr_reader :context, :canon, :spec, :top_constants, :bottom_constants, :contract_methods, :extra_methods,
                  :private_methods_data, :payload_docs, :notes

      def initialize(context)
        @context = context
        @spec = context.spec
        @canon = Canon.new
        @requires = []
        @env_constants = []
        @amount_helpers = []
        @flags = {}
        @payload_docs = {}
        @notes = []
        build
      end

      def class_name = context.class_name
      def namespace = canon.namespace
      def base_service = canon.base_service
      def requires = @requires.uniq.sort

      # Everything the pieces register while they are built.
      def require(library) = @requires << library
      def need(flag, value = :set) = (@flags[flag] = value)
      def need?(flag) = @flags.key?(flag)
      def flag(flag) = @flags[flag]
      def env_constants = @env_constants.uniq
      def add_env_constants(names) = @env_constants.concat(names)
      def amount_helpers = @amount_helpers.uniq(&:name)
      def add_amount_helpers(names) = @amount_helpers.concat(names)
      def add_notes(lines) = @notes.concat(lines)

      # The comment block at the top of the file.
      def header_lines
        provider = spec.provider
        ["Generated by provider-integrator #{VERSION} from #{provider.title.inspect} #{provider.version} " \
         "(OpenAPI #{spec.spec_format.openapi}).",
         "Contract: #{canon.base_service_class} (see INTEGRATION.md; base_contract.rb is a stub for local runs).",
         "Do not edit by hand: re-run the generator and pin corrections in overrides.yml.",
         "\"Evidence:\" comments cite the spec; \"#{Generator::Confidence::MARKER} ...)\" marks what needs " \
         "confirmation."]
      end

      # Rescue clauses shared by every method that talks to the provider (reference service shape).
      def rescues
        canon.exceptions.map { |canonical, exception| [exception, canon.failure_for_error(canonical)] }
      end

      # Scope for payloads outside the create branches (extra operations borrow the create units).
      def scope(branch: nil, method_expression: "request_method")
        Scope.build(branch:, method_expression:, fallback_conversion: create_conversion)
      end

      def create_conversion
        context.create_operation&.request_fields&.find { |field| field.canonical == "amount" }&.conversion
      end

      # Provider path of the error code in error responses (docs/IR_CONTRACT.md 4), or nil.
      def error_code_path
        return @error_code_path if defined?(@error_code_path)

        @error_code_path = declared_error_code_path || ExamplePaths.error_code(spec.operations.flat_map(&:errors))
      end

      def declared_error_code_path
        fields = spec.operations.flat_map(&:response_fields)
        fields.find { |item| item.canonical == "error.code" && !item.provider_path.include?("[]") }&.provider_path
      end

      # Provider path of the status in a success response of +operation+ (top level only), or nil.
      def status_path(operation)
        operation.response_fields.find { |field| field.canonical == "status" && !field.provider_path.include?(".") }
                 &.provider_path
      end

      def provider_id_path(operation)
        operation.response_fields.find do |field|
          field.canonical == "provider_operation_id" && !field.provider_path.include?(".")
        end&.provider_path
      end

      private

      def build
        prime_flags
        pieces = [CreateMethod, StatusMethod, CallbackMethod, ConditionsMethod].map { |piece| piece.new(self) }
        extras = ExtraMethods.new(self)
        @contract_methods = pieces.flat_map(&:public_methods_data)
        @extra_methods = extras.public_methods_data
        @private_methods_data = private_methods_of(pieces, extras)
        build_constants
      end

      # Piece helpers first, then the shared helpers (built last: they depend on what the pieces asked for).
      def private_methods_of(pieces, extras)
        pieces.flat_map(&:private_methods_data) + extras.private_methods_data + ServiceHelpers.new(self).methods_data
      end

      def build_constants
        constants = ServiceConstants.new(self)
        @top_constants = constants.top
        @bottom_constants = constants.bottom
      end

      # Facts the pieces consult before the helpers that own them are built.
      def prime_flags
        auth = spec.authentication
        need(:auth_query, auth.name) if auth.type == "api_key" && auth.location == "query"
      end
    end
  end
end
