# frozen_string_literal: true

module ProviderIntegrator
  module TemplateData
    # Everything service_spec.rb.erb prints: the RSpec file that runs the generated service against
    # fixtures.json through WebMock. Expected values are computed from the same fixtures Hash that
    # fixtures.json is written from (TemplateData::Fixtures), so the spec and the fixtures agree by
    # construction; the signature helper prints the expressions verify_signature! is built from.
    class ServiceSpec
      TOP_LEVEL = 1
      LIBRARIES = %w[json rspec webmock/rspec].freeze
      MARKER_PREFIX = "_"

      attr_reader :context, :spec, :canon, :service, :fixtures, :subject, :request

      def initialize(context)
        @context = context
        @spec = context.spec
        @canon = Canon.new
        @service = context.service_data
        @fixtures = Fixtures.new(context).to_h
        @subject = SpecSubject.new(self)
        @request = SpecRequest.new(self)
        @builders = [SpecCreateExamples, SpecStatusExamples, SpecCallbackExamples, SpecConditionExamples]
                    .map { |builder| builder.new(self) }
      end

      def class_name = "#{canon.namespace}::#{context.class_name}"
      def spec_file_name = context.spec_file_name

      # A fixtures.json example at +keys+ without the generator markers (_synthetic, _synthetic_fields),
      # or nil when the fixtures have no such entry.
      def fixture(*keys)
        value = keys.reduce(fixtures) { |acc, key| acc.is_a?(Hash) ? acc[key] : nil }
        value.is_a?(Hash) ? value.reject { |key, _| key.start_with?(MARKER_PREFIX) } : value
      end

      # { http => ErrorMapping } as ERROR_MAP of the service sees it.
      def error_mappings = @error_mappings ||= ServiceConstants.error_mappings(spec, context)

      def verifier = callback_builder.verifier

      # ---- what the template prints -----------------------------------------------------------------

      def header_lines
        ["Generated by provider-integrator #{VERSION}: RSpec for #{class_name} over " \
         "#{Generator::FixturesGenerator::FILE_NAME} through WebMock (no network).",
         "Run from this directory: rspec #{spec_file_name} (gems: rspec, webmock).",
         "#{Generator::BaseContractGenerator::FILE_NAME} (#{canon.base_service_class}, #{http_client}) is a stub " \
         "for local runs (docs/ASSUMPTIONS.md)."].flat_map { |line| Code.wrap(line) }
      end

      def requires
        libraries = LIBRARIES.dup
        libraries << "openssl" if verifier && !verifier.asymmetric?
        libraries << "uri" if request.form?
        libraries.sort
      end

      def relative_requires
        [Generator::BaseContractGenerator::FILE_NAME, context.service_file_name].map { |name| name.delete_suffix(".rb") }
      end

      def lets
        [*base_lets, *query_let, operation_let]
      end

      def befores
        return [] unless request.token?

        comment = "The OAuth2 token the service fetches before every request."
        [SpecBlock::Block.build("before", token_lines, level: TOP_LEVEL, comment:)]
      end

      def helpers
        [fixture_helper, stub_helper, sent_body_helper, operation_with_helper, *signature_helpers]
      end

      def groups = @builders.map(&:group)

      # [[method name, Russian summary, example count], ...] for INTEGRATION.md.
      def coverage = @builders.map { |builder| [builder.method_name, builder.summary, builder.count] }
      def example_count = @builders.sum(&:count)

      private

      def http_client = "#{canon.namespace}::#{BaseContract::HTTP_CLIENT}"
      def callback_builder = @builders.find { |builder| builder.is_a?(SpecCallbackExamples) }

      def let(name, lines, comment: [])
        SpecBlock::Let.build(name, lines, level: TOP_LEVEL, comment:)
      end

      def base_lets
        fixtures_file = Code.str(Generator::FixturesGenerator::FILE_NAME)
        [let("fixtures", "JSON.parse(File.read(File.join(__dir__, #{fixtures_file})))"),
         let("credentials", subject.credentials_literal),
         let("service", "described_class.new(client: #{http_client}.new, #{canon.credentials}: credentials)"),
         let("requests", "[]")]
      end

      def query_let = request.query? ? [let("auth_query", request.query_literal)] : []

      def operation_let
        comment = "The platform operation built from fixtures.json (the create request and its success response)."
        let("operation", subject.operation_lines, comment:)
      end

      def helper(name, lines, params: "", comment: [])
        MethodData.build(name:, params:, lines:, comment:, level: TOP_LEVEL)
      end

      def token_lines
        token = "{ #{Code.str(ServiceHelpers::ACCESS_TOKEN_FIELD)} => #{Code.str(SpecRequest::ACCESS_TOKEN)} }"
        ["token = #{token}", "stub_request(:post, described_class::TOKEN_URL)",
         "  .to_return(status: 200, body: JSON.generate(token), headers: { 'Content-Type' => 'application/json' })"]
      end

      def fixture_helper
        helper("fixture", ["fixtures.dig(*keys).reject { |key, _| key.start_with?(#{Code.str(MARKER_PREFIX)}) }"],
               params: "*keys",
               comment: "An example of fixtures.json without the generator markers (_synthetic, _synthetic_fields).")
      end

      def stub_helper
        query = request.query? ? ".with(query: auth_query)" : ""
        helper("stub_provider",
               ["stub_request(verb, url)#{query}.to_return do |request|", "  requests << request",
                "  { status: status, body: JSON.generate(body), headers: { 'Content-Type' => 'application/json' }" \
                ".merge(headers) }", "end"],
               params: "verb, url, status, body, headers: {}",
               comment: "Stubs one provider response and records every request the service sends to url.")
      end

      def sent_body_helper
        body = request.form? ? "URI.decode_www_form(requests.last.body).to_h" : "JSON.parse(requests.last.body)"
        helper("sent_body", [body], comment: "The body of the last request the service sent, as the provider reads it.")
      end

      def operation_with_helper
        helper("operation_with", ["#{canon.namespace}::Operation.new(**operation.to_h.merge(changes))"],
               params: "**changes", comment: "A copy of the operation with some members replaced.")
      end

      def signature_helpers
        return [] unless verifier && !verifier.asymmetric?

        [signature_for_helper, signed_payload_helper]
      end

      def signature_for_helper
        secret = canon.credential(canon.callback_secret_key)
        helper("signature_for", ["message = #{verifier.message_expression("body")}",
                                 verifier.digest_expression(secret:, message: "message")],
               params: "body",
               comment: "Signs a notification body the way verify_signature! checks it " \
                        "(#{verifier.algorithm.upcase}, #{verifier.encoding}).")
      end

      def signed_payload_helper
        comment = "The payload process_callback receives for a signed notification."
        helper("signed_payload", signed_payload_lines, params: "body", comment:)
      end

      # The platform envelope with the signature header, or the body with its signature field.
      def signed_payload_lines
        return ["body.merge(#{Code.str(verifier.name)} => signature_for(body))"] if verifier.location == "body"

        key = ->(name) { Code.str(canon.callback_key(name)) }
        Code.hash_lines(["#{key.call("body")} => body", "#{key.call("raw_body")} => JSON.generate(body)",
                         "#{key.call("headers")} => { #{Code.str(verifier.name)} => signature_for(body) }"])
      end
    end
  end
end
