# frozen_string_literal: true

# Generated by provider-integrator 0.1.0 from "CardPay Disbursement API" 2.4.0 (OpenAPI 3.1.0).
# Contract: Provider::BaseService (see INTEGRATION.md; base_contract.rb is a stub for local runs).
# Do not edit by hand: re-run the generator and pin corrections in overrides.yml.
# "Evidence:" comments cite the spec; "TODO(confidence ...)" marks what needs confirmation.

require 'json'
require 'openssl'
require 'uri'

class Provider
  class CardpayService < BaseService
    # Sandbox by default; production: https://api.cardpay.example.
    BASE_URL = ENV.fetch('CARDPAY_BASE_URL', 'https://api.sandbox.cardpay.example')

    # Sent in the request body as callback_url; configure per environment.
    CALLBACK_URL = ENV.fetch('CARDPAY_CALLBACK_URL', nil)

    # Payout methods accepted as request_method (enum of destination.type); the first is the default.
    REQUEST_METHODS = %w[card card_token].freeze

    # minimum of amount: 50000 in minor units of the provider = 500 in major units of operation.amount.
    MIN_AMOUNT = 500

    # maximum of amount: 60000000 in minor units of the provider = 600000 in major units of
    # operation.amount.
    MAX_AMOUNT = 600_000

    # Canonical requisite names each payout method needs (required in the schema, or required when the
    # method matches - see INTEGRATION.md).
    REQUIRED_REQUISITES = {
      'card'       => %w[card_number],
      'card_token' => %w[card_token]
    }.freeze

    # POST /v2/disbursements/card (createCardDisbursement).
    def create_request(operation, request_method = 'card')
      payload =
        case request_method
        when 'card' then build_card_payload(operation)
        when 'card_token' then build_card_token_payload(operation)
        end
      return failure(:unprocessable_entity, 'unsupported_request_method') if payload.nil?

      headers = auth_headers.merge(idempotency_headers(operation))
      response = client.post("#{BASE_URL}/v2/disbursements/card", json: payload, headers: headers)
      parse_create_response(operation, response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # GET /v2/disbursements/{disbursement_id} (getDisbursementState).
    def fetch_status(operation)
      response = client.get("#{BASE_URL}/v2/disbursements/#{operation.provider_operation_id}", headers: auth_headers)
      parse_status_response(operation, response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # POST /v2/notifications/disbursement (disbursementNotification); source: path_heuristic.
    # payload is the parsed JSON body, or { 'body' => body, 'headers' => headers, 'raw_body' => raw body }
    # (INTEGRATION.md, Webhook).
    def process_callback(payload)
      verify_signature!(payload) # HMAC-SHA512 from X-CardPay-Signature
      body = callback_body(payload)
      # Events without a canonical status (W203), answered as unknown_event: disbursement.in_flight
      case body['event_type']
      when 'disbursement.settled' then approve_operation(body['disbursement_id'])
      when 'disbursement.returned', 'disbursement.rejected_by_bank' then reject_operation(body['disbursement_id'],
                                                                                          body.dig('failure', 'code'))
      else failure(:unprocessable_entity, 'unknown_event')
      end
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'invalid_signature')
    end

    # Pre-checks before create_request; super runs the platform checks first.
    def check_conditions(operation, request_method)
      base_result = super
      return base_result if base_result.failed?

      unless REQUEST_METHODS.include?(request_method)
        return failure(:unprocessable_entity, 'unsupported_request_method')
      end
      # Evidence: description: копейках; error example (422): kopecks; minimum: 50000
      return failure(:unprocessable_entity, 'amount_too_low') if operation.amount < MIN_AMOUNT
      # Evidence: description: копейках; error example (422): kopecks; minimum: 50000
      return failure(:unprocessable_entity, 'amount_too_high') if operation.amount > MAX_AMOUNT

      missing = missing_requisites(operation, request_method)
      return failure(:unprocessable_entity, 'missing_requisite') unless missing.empty?

      success
    end

    # Outside the BaseService contract (kind create): POST /v2/disbursements/sbp (createSbpDisbursement).
    # Создать выплату по СБП
    def create_sbp_disbursement(operation, request_method)
      payload = build_create_sbp_disbursement_payload(operation, request_method)
      url = "#{BASE_URL}/v2/disbursements/sbp"
      response = client.post(url, json: payload, headers: auth_headers.merge(idempotency_headers(operation)))
      parse_create_sbp_disbursement_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # Outside the BaseService contract (kind cancel): POST /v2/disbursements/{disbursement_id}/cancel
    # (cancelDisbursement).
    # Отменить выплату
    def cancel_request(operation)
      url = "#{BASE_URL}/v2/disbursements/#{operation.provider_operation_id}/cancel"
      response = client.post(url, headers: auth_headers)
      parse_cancel_request_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # Outside the BaseService contract (kind balance): GET /v2/merchant/balance (getMerchantBalance).
    # Баланс мерчанта
    def fetch_balance
      url = "#{BASE_URL}/v2/merchant/balance"
      response = client.get(url, headers: auth_headers)
      parse_fetch_balance_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # Outside the BaseService contract (kind list): GET /v2/dictionaries/sbp-members (listSbpMembers).
    # Справочник банков — участников СБП
    def list_requests(params = {})
      url = "#{BASE_URL}/v2/dictionaries/sbp-members"
      url = "#{url}?#{URI.encode_www_form(params)}" unless params.empty?
      response = client.get(url, headers: auth_headers)
      parse_list_requests_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    private

    # Body of POST /v2/disbursements/card for request_method 'card' (schema CardDisbursementRequest).
    def build_card_payload(operation)
      {
        # Evidence: description: копейках; error example (422): kopecks; minimum: 50000
        amount: amount_in_minor_units(operation.amount),
        currency: 'RUB',
        merchant_reference: operation.id,
        notify_url: CALLBACK_URL,
        destination: {
          type: 'card',
          # TODO(confidence 0.6): required when destination.type = card (description: Обязателен, если type =
          # card.)
          card_number: operation.payout_requisite.dig('card', 'card_number'),
          holder_name: operation.payout_requisite.dig('card', 'name'),
          expiry: operation.payout_requisite.dig('card', 'expiry')
        }.compact
      }.compact
    end

    # Body of POST /v2/disbursements/card for request_method 'card_token' (schema
    # CardDisbursementRequest).
    def build_card_token_payload(operation)
      {
        # Evidence: description: копейках; error example (422): kopecks; minimum: 50000
        amount: amount_in_minor_units(operation.amount),
        currency: 'RUB',
        merchant_reference: operation.id,
        notify_url: CALLBACK_URL,
        destination: {
          type: 'card_token',
          # TODO(confidence 0.6): required when destination.type = card_token (description: Обязателен, если
          # type = card_token.)
          card_token: operation.payout_requisite.dig('card_token', 'card_token'),
          holder_name: operation.payout_requisite.dig('card_token', 'name'),
          expiry: operation.payout_requisite.dig('card_token', 'expiry')
        }.compact
      }.compact
    end

    # Success statuses 202, 409; everything else goes through ERROR_MAP.
    def parse_create_response(operation, response)
      body = response.body || {}
      case response.status
      # 409: duplicate by idempotency key - the provider returns the original result, treated as success.
      when 202, 409 then success(provider_operation_id: body['disbursement_id'], status: map_status(body['state']),
                                 response: body)
      else provider_error(response)
      end
    end

    def parse_status_response(operation, response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(status: map_status(body['state']), response: body)
    end

    # The parsed notification: payload['body'] under the platform envelope, else the payload itself.
    def callback_body(payload)
      payload['body'] || payload
    end

    # HMAC-SHA512 over the raw request body, base64, compared in constant time.
    # Evidence: parameter X-CardPay-Signature (header): HMAC-SHA512 от сырого тела запроса на ключе
    # callback_secret, результат в base64; operation description: Уведомление подписано: заголовок
    # `X-CardPay-Signature` содержит HMAC-SHA512 от сырого тела
    def verify_signature!(payload)
      signature = payload.dig('headers', 'X-CardPay-Signature').to_s
      message = payload['raw_body'] || JSON.generate(callback_body(payload))
      expected = [OpenSSL::HMAC.digest('SHA512', credentials[:callback_secret].to_s, message)].pack('m0')
      return if !signature.empty? && secure_compare(expected, signature)

      raise Provider::UnauthorizedError, 'invalid_signature'
    end

    def secure_compare(left, right)
      left.bytesize == right.bytesize && OpenSSL.fixed_length_secure_compare(left, right)
    end

    # Canonical requisite names the payout method needs (REQUIRED_REQUISITES) that are missing from
    # operation.payout_requisite[request_method].
    def missing_requisites(operation, request_method)
      requisite = operation.payout_requisite.to_h[request_method] || {}
      REQUIRED_REQUISITES.fetch(request_method, []).reject { |field| requisite[field] }
    end

    # Body of POST /v2/disbursements/sbp.
    def build_create_sbp_disbursement_payload(operation, request_method = nil)
      {
        # Evidence: description: копейках; minimum: 50000
        amount: amount_in_minor_units(operation.amount),
        currency: 'RUB',
        merchant_reference: operation.id,
        notify_url: CALLBACK_URL,
        destination: {
          phone: operation.payout_requisite.dig(request_method, 'phone'),
          member_id: operation.payout_requisite.dig(request_method, 'bank_code'),
          member_name: operation.payout_requisite.dig(request_method, 'member_name')
        }.compact
      }.compact
    end

    def parse_create_sbp_disbursement_response(response)
      body = response.body || {}
      return provider_error(response) unless [202, 409].include?(response.status)

      success(status: map_status(body['state']), response: body)
    end

    def parse_cancel_request_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(status: map_status(body['state']), response: body)
    end

    def parse_fetch_balance_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(response: body)
    end

    def parse_list_requests_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(response: body)
    end

    # CardPayKey: api_key in header X-CardPay-Key. Evidence: securitySchemes.CardPayKey: apiKey in header
    # X-CardPay-Key; security: CardPayKey used by 6 of 7 operations
    def auth_headers
      { 'X-CardPay-Key' => credentials[:api_key] }
    end

    # X-Request-Id (format uuid): operation.id is the stable key of the request; the provider answers a
    # repeat with the original result.
    def idempotency_headers(operation)
      { 'X-Request-Id' => operation.id.to_s }
    end

    # Provider status -> Space Payments status (STATUS_MAP); unknown values stay in_progress until the
    # next notification.
    def map_status(value)
      STATUS_MAP.fetch(value.to_s, 'in_progress')
    end

    # Error response -> failure through ERROR_MAP (HTTP status -> canonical code).
    def provider_error(response)
      body = response.body || {}
      details = { provider_code: error_code(body), retry_after: retry_after_seconds(response) }.compact
      case ERROR_MAP.fetch(response.status) { response.status >= 500 ? 'internal_error' : 'validation_error' }
      when 'invalid_credentials' then failure(:unauthorized, 'provider.invalid_credentials', **details)
      when 'insufficient_balance' then failure(:provider_error, 'provider.insufficient_balance', **details)
      when 'rate_limit' then failure(:too_many_requests, 'provider.rate_limit', **details)
      when 'internal_error' then failure(:provider_error, 'provider.internal_error', **details)
      when 'not_found' then failure(:provider_error, 'provider.not_found', **details)
      when 'conflict' then failure(:unprocessable_entity, 'provider.conflict', **details)
      else failure(:unprocessable_entity, 'provider.validation_error', **details)
      end
    end

    # Retry-After of a rate-limited response in seconds (body or header); nil when the provider sent none.
    def retry_after_seconds(response)
      header = response.headers.to_h.find { |name, _| name.to_s.casecmp?('Retry-After') }&.last
      body_value = (response.body || {})['retry_after']
      (header || body_value)&.to_i
    end

    # Provider error code of an error response (failure.code in the spec).
    def error_code(body)
      body.dig('failure', 'code')&.to_s
    end

    # operation.amount is in major units; the provider expects minor units (x 100).
    # round (not to_i) keeps 10.15 * 100 from truncating to 1014 with Float amounts.
    def amount_in_minor_units(amount)
      (amount * 100).round
    end

    # Provider status -> Space Payments status (statuses.yml); evidence per status in INTEGRATION.md.
    STATUS_MAP = {
      'queued'           => 'in_progress',
      # TODO(confidence 0.3): default: in_progress
      'in_flight'        => 'in_progress',
      'settled'          => 'approved',
      'returned'         => 'rejected',
      'rejected_by_bank' => 'rejected'
    }.freeze

    # HTTP status -> canonical error code (Space Payments); provider codes and evidence in INTEGRATION.md.
    ERROR_MAP = {
      400 => 'validation_error',
      401 => 'invalid_credentials',
      402 => 'insufficient_balance',
      404 => 'not_found',
      409 => 'conflict',
      422 => 'validation_error',
      429 => 'rate_limit',
      500 => 'internal_error',
      503 => 'internal_error'
    }.freeze

    # HTTP status -> what the platform should do (canonical_contract.yml -> actions).
    ERROR_ACTIONS = {
      400 => 'terminal_reject',
      401 => 'fatal_block_provider',
      402 => 'retry_later',
      404 => 'unknown_state',
      409 => 'conflict',
      422 => 'terminal_reject',
      429 => 'retry_with_backoff',
      500 => 'retry_alert_ops',
      503 => 'retry_later'
    }.freeze
  end
end
