# frozen_string_literal: true

# Generated by provider-integrator 0.1.0 from "NovaPay Payout API" 1.0.0 (OpenAPI 3.0.3).
# Contract: Provider::BaseService (see INTEGRATION.md; base_contract.rb is a stub for local runs).
# Do not edit by hand: re-run the generator and pin corrections in overrides.yml.
# "Evidence:" comments cite the spec; "TODO(confidence ...)" marks what needs confirmation.

require 'json'
require 'openssl'

class Provider
  class NovapayService < BaseService
    # Sandbox by default; production: https://api.novapay.example/v1.
    BASE_URL = ENV.fetch('NOVAPAY_BASE_URL', 'https://api.sandbox.novapay.example/v1')

    # Payout methods accepted as request_method (enum of recipient.type); the first is the default.
    REQUEST_METHODS = %w[sbp card].freeze

    # minimum of amount: 100000 in minor units of the provider = 1000 in major units of operation.amount.
    MIN_AMOUNT = 1000

    # Canonical requisite names each payout method needs (required in the schema, or required when the
    # method matches - see INTEGRATION.md).
    REQUIRED_REQUISITES = {
      'sbp'  => %w[phone bank_code],
      'card' => %w[phone card_number]
    }.freeze

    # POST /payouts (createPayout).
    def create_request(operation, request_method = 'sbp')
      payload =
        case request_method
        when 'sbp' then build_sbp_payload(operation)
        when 'card' then build_card_payload(operation)
        end
      return failure(:unprocessable_entity, 'unsupported_request_method') if payload.nil?

      headers = auth_headers.merge(idempotency_headers(operation))
      response = client.post("#{BASE_URL}/payouts", json: payload, headers: headers)
      parse_create_response(operation, response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # GET /payouts/{payout_id} (getPayoutStatus).
    def fetch_status(operation)
      response = client.get("#{BASE_URL}/payouts/#{operation.provider_operation_id}", headers: auth_headers)
      parse_status_response(operation, response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # POST /webhooks/payout (payoutWebhook); source: path_heuristic.
    # payload is the parsed JSON body, or { 'body' => body, 'headers' => headers, 'raw_body' => raw body }
    # (INTEGRATION.md, Webhook).
    def process_callback(payload)
      verify_signature!(payload) # HMAC-SHA256 from X-NovaPay-Signature
      body = callback_body(payload)
      case body['event']
      when 'payout.completed' then approve_operation(body['payout_id'])
      when 'payout.failed', 'payout.cancelled' then reject_operation(body['payout_id'], body.dig('error', 'code'))
      when 'payout.processing' then success(status: 'in_progress', response: body)
      else failure(:unprocessable_entity, 'unknown_event')
      end
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'invalid_signature')
    end

    # Pre-checks before create_request; super runs the platform checks first.
    def check_conditions(operation, request_method)
      base_result = super
      return base_result if base_result.failed?

      unless REQUEST_METHODS.include?(request_method)
        return failure(:unprocessable_entity, 'unsupported_request_method')
      end
      # Evidence: description: копейках; error example (422): kopecks; minimum: 100000
      return failure(:unprocessable_entity, 'amount_too_low') if operation.amount < MIN_AMOUNT

      missing = missing_requisites(operation, request_method)
      return failure(:unprocessable_entity, 'missing_requisite') unless missing.empty?

      success
    end

    # Outside the BaseService contract (kind cancel): POST /payouts/{payout_id}/cancel (cancelPayout).
    # Отменить выплату
    def cancel_request(operation)
      url = "#{BASE_URL}/payouts/#{operation.provider_operation_id}/cancel"
      response = client.post(url, headers: auth_headers)
      parse_cancel_request_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # Outside the BaseService contract (kind balance): GET /balance (getBalance).
    # Баланс провайдера
    def fetch_balance
      url = "#{BASE_URL}/balance"
      response = client.get(url, headers: auth_headers)
      parse_fetch_balance_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    private

    # Body of POST /payouts for request_method 'sbp' (schema CreatePayoutRequest).
    def build_sbp_payload(operation)
      {
        # Evidence: description: копейках; error example (422): kopecks; minimum: 100000
        amount: amount_in_minor_units(operation.amount),
        currency: 'RUB',
        external_id: operation.id,
        recipient: {
          type: 'sbp',
          phone: operation.payout_requisite.dig('sbp', 'phone'),
          # TODO(confidence 0.6): required when recipient.type = sbp (description: обязателен для type=sbp)
          bank_code: operation.payout_requisite.dig('sbp', 'bank_code'),
          bank_name: operation.payout_requisite.dig('sbp', 'bank_name')
        }.compact
      }.compact
    end

    # Body of POST /payouts for request_method 'card' (schema CreatePayoutRequest).
    def build_card_payload(operation)
      {
        # Evidence: description: копейках; error example (422): kopecks; minimum: 100000
        amount: amount_in_minor_units(operation.amount),
        currency: 'RUB',
        external_id: operation.id,
        recipient: {
          type: 'card',
          phone: operation.payout_requisite.dig('card', 'phone'),
          bank_name: operation.payout_requisite.dig('card', 'bank_name'),
          # TODO(confidence 0.6): required when recipient.type = card (description: обязателен для type=card)
          card_number: operation.payout_requisite.dig('card', 'card_number')
        }.compact
      }.compact
    end

    # Success statuses 201, 409; everything else goes through ERROR_MAP.
    def parse_create_response(operation, response)
      body = response.body || {}
      case response.status
      # 409: duplicate by idempotency key - the provider returns the original result, treated as success.
      when 201, 409 then success(provider_operation_id: body['id'], status: map_status(body['status']), response: body)
      else provider_error(response)
      end
    end

    def parse_status_response(operation, response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(status: map_status(body['status']), response: body)
    end

    # The parsed notification: payload['body'] under the platform envelope, else the payload itself.
    def callback_body(payload)
      payload['body'] || payload
    end

    # HMAC-SHA256 over the raw request body, hex, compared in constant time.
    # Evidence: parameter X-NovaPay-Signature (header): HMAC-SHA256 подпись тела запроса; operation
    # description: Подпись передаётся в заголовке X-NovaPay-Signature (HMAC-SHA256)
    # TODO(confidence 0.6): encoding and canonicalization are not in the spec (W301): hex over raw_body
    # assumed
    def verify_signature!(payload)
      signature = payload.dig('headers', 'X-NovaPay-Signature').to_s
      message = payload['raw_body'] || JSON.generate(callback_body(payload))
      expected = OpenSSL::HMAC.hexdigest('SHA256', credentials[:callback_secret].to_s, message)
      return if !signature.empty? && secure_compare(expected, signature)

      raise Provider::UnauthorizedError, 'invalid_signature'
    end

    def secure_compare(left, right)
      left.bytesize == right.bytesize && OpenSSL.fixed_length_secure_compare(left, right)
    end

    # Canonical requisite names the payout method needs (REQUIRED_REQUISITES) that are missing from
    # operation.payout_requisite[request_method].
    def missing_requisites(operation, request_method)
      requisite = operation.payout_requisite.to_h[request_method] || {}
      REQUIRED_REQUISITES.fetch(request_method, []).reject { |field| requisite[field] }
    end

    def parse_cancel_request_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(status: map_status(body['status']), response: body)
    end

    def parse_fetch_balance_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(response: body)
    end

    # ApiKeyAuth: api_key in header X-API-Key. Evidence: securitySchemes.ApiKeyAuth: apiKey in header
    # X-API-Key; security: ApiKeyAuth used by 4 of 5 operations
    def auth_headers
      { 'X-API-Key' => credentials[:api_key] }
    end

    # Idempotency-Key (format uuid): operation.id is the stable key of the request; the provider answers a
    # repeat with the original result.
    def idempotency_headers(operation)
      { 'Idempotency-Key' => operation.id.to_s }
    end

    # Provider status -> Space Payments status (STATUS_MAP); unknown values stay in_progress until the
    # next notification.
    def map_status(value)
      STATUS_MAP.fetch(value.to_s, 'in_progress')
    end

    # Error response -> failure through ERROR_MAP (HTTP status -> canonical code).
    def provider_error(response)
      body = response.body || {}
      details = { provider_code: error_code(body), retry_after: retry_after_seconds(response) }.compact
      case ERROR_MAP.fetch(response.status) { response.status >= 500 ? 'internal_error' : 'validation_error' }
      when 'invalid_credentials' then failure(:unauthorized, 'provider.invalid_credentials', **details)
      when 'insufficient_balance' then failure(:provider_error, 'provider.insufficient_balance', **details)
      when 'rate_limit' then failure(:too_many_requests, 'provider.rate_limit', **details)
      when 'internal_error' then failure(:provider_error, 'provider.internal_error', **details)
      when 'not_found' then failure(:provider_error, 'provider.not_found', **details)
      when 'conflict' then failure(:unprocessable_entity, 'provider.conflict', **details)
      else failure(:unprocessable_entity, 'provider.validation_error', **details)
      end
    end

    # Retry-After of a rate-limited response in seconds (header); nil when the provider sent none.
    def retry_after_seconds(response)
      header = response.headers.to_h.find { |name, _| name.to_s.casecmp?('Retry-After') }&.last
      header&.to_i
    end

    # Provider error code of an error response (error.code in the spec).
    def error_code(body)
      body.dig('error', 'code')&.to_s
    end

    # operation.amount is in major units; the provider expects minor units (x 100).
    # round (not to_i) keeps 10.15 * 100 from truncating to 1014 with Float amounts.
    def amount_in_minor_units(amount)
      (amount * 100).round
    end

    # Provider status -> Space Payments status (statuses.yml); evidence per status in INTEGRATION.md.
    STATUS_MAP = {
      'pending'    => 'in_progress',
      'processing' => 'in_progress',
      'completed'  => 'approved',
      'failed'     => 'rejected',
      'cancelled'  => 'rejected'
    }.freeze

    # HTTP status -> canonical error code (Space Payments); provider codes and evidence in INTEGRATION.md.
    ERROR_MAP = {
      400 => 'validation_error',
      401 => 'invalid_credentials',
      402 => 'insufficient_balance',
      404 => 'not_found',
      409 => 'conflict',
      422 => 'validation_error',
      429 => 'rate_limit',
      500 => 'internal_error'
    }.freeze

    # HTTP status -> what the platform should do (canonical_contract.yml -> actions).
    ERROR_ACTIONS = {
      400 => 'terminal_reject',
      401 => 'fatal_block_provider',
      402 => 'retry_later',
      404 => 'unknown_state',
      409 => 'conflict',
      422 => 'terminal_reject',
      429 => 'retry_with_backoff',
      500 => 'retry_alert_ops'
    }.freeze
  end
end
