# frozen_string_literal: true

# Generated by provider-integrator 0.1.0 from "Tranzo Disbursement API" 2.4.1 (OpenAPI 3.0.3).
# Contract: Provider::BaseService (see INTEGRATION.md; base_contract.rb is a stub for local runs).
# Do not edit by hand: re-run the generator and pin corrections in overrides.yml.
# "Evidence:" comments cite the spec; "TODO(confidence ...)" marks what needs confirmation.

require 'openssl'
require 'uri'

class Provider
  class TranzoService < BaseService
    # Sandbox by default; production: https://api.tranzo.example/disbursement/v2.
    BASE_URL = ENV.fetch('TRANZO_BASE_URL', 'https://api.sandbox.tranzo.example/disbursement/v2')

    # OAuth2 token endpoint (securitySchemes).
    TOKEN_URL = ENV.fetch('TRANZO_TOKEN_URL', 'https://auth.tranzo.example/oauth2/token')

    # Sent in the request body as callback_url; configure per environment.
    CALLBACK_URL = ENV.fetch('TRANZO_CALLBACK_URL', nil)

    # Payout methods accepted as request_method (enum of destination.kind); the first is the default.
    REQUEST_METHODS = %w[phone card account].freeze

    # minimum of amount: 50000 in minor units of the provider = 500 in major units of operation.amount.
    MIN_AMOUNT = 500

    # maximum of amount: 300000000 in minor units of the provider = 3000000 in major units of
    # operation.amount.
    MAX_AMOUNT = 3_000_000

    # Canonical requisite names each payout method needs (required in the schema, or required when the
    # method matches - see INTEGRATION.md).
    REQUIRED_REQUISITES = {
      'phone'   => %w[phone],
      'card'    => %w[card_number],
      'account' => %w[account_number bank_code]
    }.freeze

    # POST /disbursements (registerDisbursement).
    def create_request(operation, request_method = 'phone')
      payload =
        case request_method
        when 'phone' then build_phone_payload(operation)
        when 'card' then build_card_payload(operation)
        when 'account' then build_account_payload(operation)
        end
      return failure(:unprocessable_entity, 'unsupported_request_method') if payload.nil?

      headers = auth_headers.merge(idempotency_headers(operation))
      response = client.post("#{BASE_URL}/disbursements", json: payload, headers: headers)
      parse_create_response(operation, response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # GET /disbursements/{operationId} (getDisbursementState).
    def fetch_status(operation)
      response = client.get("#{BASE_URL}/disbursements/#{operation.provider_operation_id}", headers: auth_headers)
      parse_status_response(operation, response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # POST {$request.body#/callbackUrl} (disbursementStateCallback); source: callbacks.
    # payload is the parsed JSON body, or { 'body' => body, 'headers' => headers, 'raw_body' => raw body }
    # (INTEGRATION.md, Webhook).
    def process_callback(payload)
      verify_signature!(payload) # HMAC-SHA512 from sign
      body = callback_body(payload)
      # Events without a canonical status (W203), answered as unknown_event: disbursement.revoked
      case body['event']
      when 'disbursement.executed' then approve_operation(body['operationId'])
      when 'disbursement.declined', 'disbursement.expired', 'disbursement.failed' then reject_operation(
        body['operationId'], body['errorCode']
      )
      else failure(:unprocessable_entity, 'unknown_event')
      end
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'invalid_signature')
    end

    # Pre-checks before create_request; super runs the platform checks first.
    def check_conditions(operation, request_method)
      base_result = super
      return base_result if base_result.failed?

      unless REQUEST_METHODS.include?(request_method)
        return failure(:unprocessable_entity, 'unsupported_request_method')
      end
      # Evidence: description: копейках; error example (422): копеек; minimum: 50000
      return failure(:unprocessable_entity, 'amount_too_low') if operation.amount < MIN_AMOUNT
      # Evidence: description: копейках; error example (422): копеек; minimum: 50000
      return failure(:unprocessable_entity, 'amount_too_high') if operation.amount > MAX_AMOUNT

      missing = missing_requisites(operation, request_method)
      return failure(:unprocessable_entity, 'missing_requisite') unless missing.empty?

      success
    end

    # Outside the BaseService contract (kind list): GET /disbursements (listDisbursements).
    # Реестр выплат за период
    def list_requests(params = {})
      url = "#{BASE_URL}/disbursements"
      url = "#{url}?#{URI.encode_www_form(params)}" unless params.empty?
      response = client.get(url, headers: auth_headers)
      parse_list_requests_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # Outside the BaseService contract (kind cancel): POST /disbursements/{operationId}/revoke
    # (revokeDisbursement).
    # Отозвать выплату
    def cancel_request(operation)
      url = "#{BASE_URL}/disbursements/#{operation.provider_operation_id}/revoke"
      response = client.post(url, headers: auth_headers.merge(idempotency_headers(operation)))
      parse_cancel_request_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # Outside the BaseService contract (kind unknown): POST /fees/quote (quoteDisbursementFee).
    # Предварительный расчёт комиссии
    # TODO(confidence 0.0): operation kind unknown with confidence 0.0
    def quote_disbursement_fee(operation, request_method)
      payload = build_quote_disbursement_fee_payload(operation, request_method)
      url = "#{BASE_URL}/fees/quote"
      response = client.post(url, json: payload, headers: auth_headers)
      parse_quote_disbursement_fee_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # Outside the BaseService contract (kind balance): GET /merchant/balance (getMerchantBalance).
    # Баланс мерчанта
    def fetch_balance
      url = "#{BASE_URL}/merchant/balance"
      response = client.get(url, headers: auth_headers)
      parse_fetch_balance_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    private

    # Body of POST /disbursements for request_method 'phone' (schema DisbursementRequest).
    def build_phone_payload(operation)
      {
        merchantReference: operation.id,
        # Evidence: description: копейках; error example (422): копеек; minimum: 50000
        amount: amount_in_minor_units(operation.amount),
        currency: operation.currency,
        destination: {
          kind: 'phone',
          # TODO(confidence 0.6): required when destination.kind = phone (description: Обязательно, если kind =
          # phone)
          phone: operation.payout_requisite.dig('phone', 'phone'),
          holderName: operation.payout_requisite.dig('phone', 'name')
        }.compact,
        callbackUrl: CALLBACK_URL
      }.compact
    end

    # Body of POST /disbursements for request_method 'card' (schema DisbursementRequest).
    def build_card_payload(operation)
      {
        merchantReference: operation.id,
        # Evidence: description: копейках; error example (422): копеек; minimum: 50000
        amount: amount_in_minor_units(operation.amount),
        currency: operation.currency,
        destination: {
          kind: 'card',
          # TODO(confidence 0.6): required when destination.kind = card (description: Обязательно, если kind =
          # card)
          cardNumber: operation.payout_requisite.dig('card', 'card_number'),
          holderName: operation.payout_requisite.dig('card', 'name')
        }.compact,
        callbackUrl: CALLBACK_URL
      }.compact
    end

    # Body of POST /disbursements for request_method 'account' (schema DisbursementRequest).
    def build_account_payload(operation)
      {
        merchantReference: operation.id,
        # Evidence: description: копейках; error example (422): копеек; minimum: 50000
        amount: amount_in_minor_units(operation.amount),
        currency: operation.currency,
        destination: {
          kind: 'account',
          # TODO(confidence 0.6): required when destination.kind = account (description: Обязательно, если kind
          # = account)
          accountNumber: operation.payout_requisite.dig('account', 'account_number'),
          # TODO(confidence 0.6): required when destination.kind = account (description: Обязательно, если kind
          # = account)
          bic: operation.payout_requisite.dig('account', 'bank_code'),
          holderName: operation.payout_requisite.dig('account', 'name')
        }.compact,
        callbackUrl: CALLBACK_URL
      }.compact
    end

    # Success statuses 202; everything else goes through ERROR_MAP.
    def parse_create_response(operation, response)
      body = response.body || {}
      case response.status
      when 202 then success(provider_operation_id: body['operationId'], status: map_status(body['state']),
                            response: body)
      else provider_error(response)
      end
    end

    def parse_status_response(operation, response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(status: map_status(body['state']), response: body)
    end

    # The parsed notification: payload['body'] under the platform envelope, else the payload itself.
    def callback_body(payload)
      payload['body'] || payload
    end

    # HMAC-SHA512 over the payload values concatenated, hex, compared in constant time.
    # Evidence: field sign: Подпись уведомления: HMAC-SHA512 в нижнем регистре hex от concatenation;
    # operation description: sign = HMAC-SHA512 в нижнем регистре hex от concatenation значений
    # TODO(confidence 0.5): field order of the signature base string is not in the spec; values sorted by
    # key assumed
    def verify_signature!(payload)
      signature = callback_body(payload)['sign'].to_s
      message = callback_body(payload).except('sign').sort.map { |_, value| value.to_s }.join
      expected = OpenSSL::HMAC.hexdigest('SHA512', credentials[:callback_secret].to_s, message)
      return if !signature.empty? && secure_compare(expected, signature)

      raise Provider::UnauthorizedError, 'invalid_signature'
    end

    def secure_compare(left, right)
      left.bytesize == right.bytesize && OpenSSL.fixed_length_secure_compare(left, right)
    end

    # Canonical requisite names the payout method needs (REQUIRED_REQUISITES) that are missing from
    # operation.payout_requisite[request_method].
    def missing_requisites(operation, request_method)
      requisite = operation.payout_requisite.to_h[request_method] || {}
      REQUIRED_REQUISITES.fetch(request_method, []).reject { |field| requisite[field] }
    end

    def parse_list_requests_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(response: body)
    end

    def parse_cancel_request_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(status: map_status(body['state']), response: body)
    end

    # Body of POST /fees/quote.
    def build_quote_disbursement_fee_payload(operation, request_method = nil)
      {
        # Evidence: description: копейках; error example (422): копеек; minimum: 50000
        # Units assumed equal to create_request (not analysed for this operation)
        amount: amount_in_minor_units(operation.amount),
        currency: operation.currency,
        method: request_method
      }.compact
    end

    def parse_quote_disbursement_fee_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(response: body)
    end

    def parse_fetch_balance_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(response: body)
    end

    # MerchantOAuth2: oauth2_client_credentials in header Authorization. Evidence:
    # securitySchemes.MerchantOAuth2: oauth2 in header Authorization (clientCredentials
    # https://auth.tranzo.example/oauth2/token); security: MerchantOAuth2 used by 6 of 6 operations
    def auth_headers
      { 'Authorization' => "Bearer #{access_token}" }
    end

    # OAuth2 client credentials at TOKEN_URL (scopes: disbursements:write, disbursements:read,
    # merchant:read).
    # TODO(confidence 0.6): cache the token until it expires; the spec does not state the lifetime
    def access_token
      form = { grant_type: 'client_credentials', client_id: credentials[:client_id],
client_secret: credentials[:client_secret], scope: 'disbursements:write disbursements:read merchant:read' }
      response = client.post(TOKEN_URL, form: form, headers: {})
      response.body.to_h['access_token']
    end

    # X-Request-Id (format uuid): operation.id is the stable key of the request; the provider answers a
    # repeat with the original result.
    def idempotency_headers(operation)
      { 'X-Request-Id' => operation.id.to_s }
    end

    # Provider status -> Space Payments status (STATUS_MAP); unknown values stay in_progress until the
    # next notification.
    def map_status(value)
      STATUS_MAP.fetch(value.to_s, 'in_progress')
    end

    # Error response -> failure through ERROR_MAP (HTTP status -> canonical code).
    def provider_error(response)
      details = { retry_after: retry_after_seconds(response) }.compact
      case ERROR_MAP.fetch(response.status) { response.status >= 500 ? 'internal_error' : 'validation_error' }
      when 'invalid_credentials' then failure(:unauthorized, 'provider.invalid_credentials', **details)
      when 'insufficient_balance' then failure(:provider_error, 'provider.insufficient_balance', **details)
      when 'rate_limit' then failure(:too_many_requests, 'provider.rate_limit', **details)
      when 'internal_error' then failure(:provider_error, 'provider.internal_error', **details)
      when 'not_found' then failure(:provider_error, 'provider.not_found', **details)
      when 'conflict' then failure(:unprocessable_entity, 'provider.conflict', **details)
      else failure(:unprocessable_entity, 'provider.validation_error', **details)
      end
    end

    # Retry-After of a rate-limited response in seconds (body); nil when the provider sent none.
    def retry_after_seconds(response)
      body_value = (response.body || {})['retryAfterSeconds']
      body_value&.to_i
    end

    # operation.amount is in major units; the provider expects minor units (x 100).
    # round (not to_i) keeps 10.15 * 100 from truncating to 1014 with Float amounts.
    def amount_in_minor_units(amount)
      (amount * 100).round
    end

    # Provider status -> Space Payments status (statuses.yml); evidence per status in INTEGRATION.md.
    STATUS_MAP = {
      # TODO(confidence 0.7): description: 0 — в обработке
      '0'  => 'in_progress',
      # TODO(confidence 0.7): description: 1 — успешно исполнена
      '1'  => 'approved',
      # TODO(confidence 0.7): description: 2 — отклонена банком получателя
      '2'  => 'rejected',
      # TODO(confidence 0.7): description: 3 — отменена мерчантом
      '3'  => 'rejected',
      # TODO(confidence 0.7): description: 4 — просрочена
      '4'  => 'rejected',
      # TODO(confidence 0.5): statuses.yml numeric: -1 -> rejected
      '-1' => 'rejected'
    }.freeze

    # HTTP status -> canonical error code (Space Payments); provider codes and evidence in INTEGRATION.md.
    ERROR_MAP = {
      400 => 'validation_error',
      401 => 'invalid_credentials',
      402 => 'insufficient_balance',
      403 => 'invalid_credentials',
      404 => 'not_found',
      409 => 'conflict',
      422 => 'validation_error',
      429 => 'rate_limit',
      500 => 'internal_error',
      503 => 'internal_error'
    }.freeze

    # HTTP status -> what the platform should do (canonical_contract.yml -> actions).
    ERROR_ACTIONS = {
      400 => 'terminal_reject',
      401 => 'fatal_block_provider',
      402 => 'retry_later',
      403 => 'fatal_block_provider',
      404 => 'unknown_state',
      409 => 'conflict',
      422 => 'terminal_reject',
      429 => 'retry_with_backoff',
      500 => 'retry_alert_ops',
      503 => 'retry_later'
    }.freeze
  end
end
