# frozen_string_literal: true

# Generated by provider-integrator 0.1.0: RSpec for Provider::TranzoService over fixtures.json through
# WebMock (no network).
# Run from this directory: rspec tranzo_service_spec.rb (gems: rspec, webmock).
# base_contract.rb (Provider::BaseService, Provider::HttpClient) is a stub for local runs
# (docs/ASSUMPTIONS.md).

require 'json'
require 'openssl'
require 'rspec'
require 'webmock/rspec'
require_relative 'base_contract'
require_relative 'tranzo_service'

RSpec.describe Provider::TranzoService do
  let(:fixtures) { JSON.parse(File.read(File.join(__dir__, 'fixtures.json'))) }
  let(:credentials) do
    { client_id: 'test-client_id', client_secret: 'test-client_secret', callback_secret: 'test-callback_secret' }
  end
  let(:service) { described_class.new(client: Provider::HttpClient.new, credentials: credentials) }
  let(:requests) { [] }
  # The platform operation built from fixtures.json (the create request and its success response).
  let(:operation) do
    Provider::Operation.new(
      id: 'MR-2026-004471',
      amount: 2500,
      currency: 'RUB',
      provider_operation_id: 'd9f2c41e-77aa-4d19-8f01-2b3c5a6d7e80',
      payout_requisite: { 'phone' => { 'phone' => '+79261234567', 'name' => 'Иванов Иван Иванович' } }
    )
  end

  # The OAuth2 token the service fetches before every request.
  before do
    token = { 'access_token' => 'test-access-token' }
    stub_request(:post, described_class::TOKEN_URL)
      .to_return(status: 200, body: JSON.generate(token), headers: { 'Content-Type' => 'application/json' })
  end

  # An example of fixtures.json without the generator markers (_synthetic, _synthetic_fields).
  def fixture(*keys)
    fixtures.dig(*keys).reject { |key, _| key.start_with?('_') }
  end

  # Stubs one provider response and records every request the service sends to url.
  def stub_provider(verb, url, status, body, headers: {})
    stub_request(verb, url).to_return do |request|
      requests << request
      { status: status, body: JSON.generate(body), headers: { 'Content-Type' => 'application/json' }.merge(headers) }
    end
  end

  # The body of the last request the service sent, as the provider reads it.
  def sent_body
    JSON.parse(requests.last.body)
  end

  # A copy of the operation with some members replaced.
  def operation_with(**changes)
    Provider::Operation.new(**operation.to_h, **changes)
  end

  # Signs a notification body the way verify_signature! checks it (HMAC-SHA512, hex).
  def signature_for(body)
    message = body.except('sign').sort.map { |_, value| value.to_s }.join
    OpenSSL::HMAC.hexdigest('SHA512', credentials[:callback_secret], message)
  end

  # The payload process_callback receives for a signed notification.
  def signed_payload(body)
    body.merge('sign' => signature_for(body))
  end

  describe '#create_request' do
    let(:url) { "#{described_class::BASE_URL}/disbursements" }
    let(:request_headers) do
      { 'Authorization' => 'Bearer test-access-token', 'X-Request-Id' => 'MR-2026-004471' }
    end

    it 'POSTs the create request of fixtures.json with the auth headers' do
      stub_provider(:post, url, 202, fixture('create_request', 'response_202'))

      service.create_request(operation, 'phone')

      expect(a_request(:post, url).with(headers: request_headers)).to have_been_made.once
      expect(sent_body).to include(
        'merchantReference' => 'MR-2026-004471',
        'amount'            => 250_000,
        'currency'          => 'RUB'
      )
      expect(sent_body['destination']).to include(
        'kind'       => 'phone',
        'phone'      => '+79261234567',
        'holderName' => 'Иванов Иван Иванович'
      )
    end

    it 'returns success with the provider id and the mapped status of response_202' do
      stub_provider(:post, url, 202, fixture('create_request', 'response_202'))

      result = service.create_request(operation, 'phone')

      expect(result).to be_success
      expect(result.provider_operation_id).to eq('d9f2c41e-77aa-4d19-8f01-2b3c5a6d7e80')
      expect(result.status).to eq('in_progress')
    end

    it 'maps HTTP 400 to failure(:unprocessable_entity, provider.validation_error)' do
      stub_provider(:post, url, 400, fixture('create_request', 'response_400'))

      result = service.create_request(operation, 'phone')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'provider.validation_error'])
    end

    it 'maps HTTP 401 to failure(:unauthorized, provider.invalid_credentials)' do
      stub_provider(:post, url, 401, fixture('create_request', 'response_401'))

      result = service.create_request(operation, 'phone')

      expect([result.error, result.code]).to eq([:unauthorized, 'provider.invalid_credentials'])
    end

    it 'maps HTTP 402 to failure(:provider_error, provider.insufficient_balance)' do
      stub_provider(:post, url, 402, fixture('create_request', 'response_402'))

      result = service.create_request(operation, 'phone')

      expect([result.error, result.code]).to eq([:provider_error, 'provider.insufficient_balance'])
    end

    it 'maps HTTP 409 to failure(:unprocessable_entity, provider.conflict)' do
      stub_provider(:post, url, 409, fixture('create_request', 'response_409'))

      result = service.create_request(operation, 'phone')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'provider.conflict'])
    end

    it 'maps HTTP 422 to failure(:unprocessable_entity, provider.validation_error)' do
      stub_provider(:post, url, 422, fixture('create_request', 'response_422'))

      result = service.create_request(operation, 'phone')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'provider.validation_error'])
    end

    it 'maps HTTP 429 to failure(:too_many_requests, provider.rate_limit)' do
      stub_provider(:post, url, 429, fixture('create_request', 'response_429'))

      result = service.create_request(operation, 'phone')

      expect([result.error, result.code]).to eq([:too_many_requests, 'provider.rate_limit'])
      expect(result.details[:retry_after]).to eq(30)
    end

    it 'maps HTTP 500 to failure(:provider_error, provider.internal_error)' do
      stub_provider(:post, url, 500, fixture('create_request', 'response_500'))

      result = service.create_request(operation, 'phone')

      expect([result.error, result.code]).to eq([:provider_error, 'provider.internal_error'])
    end

    it 'maps HTTP 503 to failure(:provider_error, provider.internal_error)' do
      stub_provider(:post, url, 503, fixture('create_request', 'response_503'))

      result = service.create_request(operation, 'phone')

      expect([result.error, result.code]).to eq([:provider_error, 'provider.internal_error'])
    end

    it 'refuses an unknown request_method without calling the provider' do
      result = service.create_request(operation, 'unsupported')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'unsupported_request_method'])
      expect(WebMock).not_to have_requested(:any, /./)
    end
  end

  describe '#fetch_status' do
    let(:url) { "#{described_class::BASE_URL}/disbursements/#{operation.provider_operation_id}" }

    it 'GETs the operation with the auth headers and maps the status of response_200' do
      stub_provider(:get, url, 200, fixture('fetch_status', 'response_200'))

      result = service.fetch_status(operation)

      expect(a_request(:get,
                       url).with(headers: { 'Authorization' => 'Bearer test-access-token' })).to have_been_made.once
      expect(result).to be_success
      expect(result.status).to eq('rejected')
    end

    it 'maps HTTP 401 to failure(:unauthorized, provider.invalid_credentials)' do
      stub_provider(:get, url, 401, fixture('fetch_status', 'response_401'))

      result = service.fetch_status(operation)

      expect([result.error, result.code]).to eq([:unauthorized, 'provider.invalid_credentials'])
    end

    it 'maps HTTP 404 to failure(:provider_error, provider.not_found)' do
      stub_provider(:get, url, 404, fixture('fetch_status', 'response_404'))

      result = service.fetch_status(operation)

      expect([result.error, result.code]).to eq([:provider_error, 'provider.not_found'])
    end

    it 'maps HTTP 429 to failure(:too_many_requests, provider.rate_limit)' do
      stub_provider(:get, url, 429, fixture('fetch_status', 'response_429'))

      result = service.fetch_status(operation)

      expect([result.error, result.code]).to eq([:too_many_requests, 'provider.rate_limit'])
      expect(result.details[:retry_after]).to eq(30)
    end
  end

  describe '#process_callback' do
    it 'approves the operation for the callback fixture (event disbursement.executed)' do
      result = service.process_callback(signed_payload(fixture('callback', 'payload')))

      expect(result).to be_success
      expect(result.status).to eq('approved')
      expect(result.provider_operation_id).to eq('d9f2c41e-77aa-4d19-8f01-2b3c5a6d7e80')
    end

    it 'rejects the operation for the callback_failed fixture (event disbursement.declined)' do
      result = service.process_callback(signed_payload(fixture('callback_failed', 'payload')))

      expect(result).to be_success
      expect(result.status).to eq('rejected')
      expect(result.provider_operation_id).to eq('d9f2c41e-77aa-4d19-8f01-2b3c5a6d7e80')
      expect(result.details[:error_code]).to eq('VAL_INVALID_DESTINATION')
    end

    it 'refuses a payload whose signature does not verify' do
      payload = signed_payload(fixture('callback', 'payload'))
      payload['sign'] = 'invalid'

      result = service.process_callback(payload)

      expect([result.error, result.code]).to eq([:unauthorized, 'invalid_signature'])
    end
  end

  describe '#check_conditions' do
    it 'accepts the operation built from fixtures.json' do
      expect(service.check_conditions(operation, 'phone')).to be_success
    end

    it 'refuses an amount below MIN_AMOUNT' do
      result = service.check_conditions(operation_with(amount: described_class::MIN_AMOUNT - 1), 'phone')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'amount_too_low'])
    end

    it 'refuses an amount above MAX_AMOUNT' do
      result = service.check_conditions(operation_with(amount: described_class::MAX_AMOUNT + 1), 'phone')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'amount_too_high'])
    end

    it 'refuses an operation without the requisites of REQUIRED_REQUISITES' do
      result = service.check_conditions(operation_with(payout_requisite: {}), 'phone')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'missing_requisite'])
    end

    it 'refuses a request_method outside REQUEST_METHODS' do
      result = service.check_conditions(operation, 'unsupported')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'unsupported_request_method'])
    end
  end
end
