# frozen_string_literal: true

# Rich, valid example Hashes for the leaf IR models (Symbol keys on purpose: from_h must accept both).
module ModelExamples
  CORE = {
    "Event" => { code: "W402", level: "warning", message: "Conditional requirement inferred",
                 location: "#/components/schemas/Recipient/properties/bank_code",
                 details: { "field" => "recipient.bank_code", "when" => "recipient.type", "equals" => "sbp" } },
    "Provider" => { title: "NovaPay Payout API", slug: "novapay", version: "1.0.0",
                    description: "Mock API for the hackathon" },
    "SpecFormat" => { openapi: "3.0.3", converted_from: nil },
    "Server" => { url: "https://api.sandbox.novapay.example/v1", description: "Sandbox", environment: "sandbox" },
    "AuthAlternative" => { scheme_name: "BearerAuth", type: "http_bearer", location: "header", name: "Authorization" },
    "Authentication" => { type: "api_key", scheme_name: "ApiKeyAuth", location: "header", name: "X-API-Key",
                          bearer_format: nil, token_url: nil, scopes: [], credentials_key: "api_key", confidence: 1.0,
                          evidence: ["securitySchemes.ApiKeyAuth: apiKey in header X-API-Key"],
                          source: "security_schemes",
                          alternatives: [{ scheme_name: "BearerAuth", type: "http_bearer", location: "header",
                                           name: "Authorization" }] },
    "Classification" => { confidence: 0.9, source: "scoring",
                          scores: { "create" => 9, "status" => 0, "cancel" => 0, "balance" => 0, "webhook" => 0,
                                    "refund" => 0, "list" => 0 },
                          evidence: ["operation_id: create -> create +5"] },
    "Idempotency" => { location: "header", name: "Idempotency-Key", required: false, format: "uuid" },
    "Parameter" => { name: "payout_id", in: "path", required: true, type: "string", format: nil, description: nil,
                     example: "np_7f3a9b2c", enum: nil, canonical: "provider_operation_id" },
    "RequestBody" => { content_type: "application/json", required: true, schema_name: "CreatePayoutRequest",
                       example: { "amount" => 1_500_000, "currency" => "RUB" },
                       examples: { "sbp_payout" => { "amount" => 1_500_000, "currency" => "RUB" } } },
    "Conversion" => { type: "multiply", value: 100, unit_from: "major", unit_to: "minor", confidence: 0.92,
                      evidence: ["description: копейках", "minimum: 100000", "422 example: kopecks"],
                      source: "scoring" },
    "ConditionalRequired" => { when: "recipient.type", equals: "sbp", source: "description", confidence: 0.6,
                               evidence: ["description: обязателен для type=sbp"] },
    "Branch" => { discriminator_path: "recipient.type", value: "card" },
    "ResponseHeader" => { name: "Retry-After", type: "integer", description: "Seconds", canonical: "retry_after" },
    "ErrorMapping" => { http: 429, provider_code: "rate_limit_exceeded", canonical: "rate_limit",
                        action: "retry_with_backoff", retry_after: "header", description: "Too many requests",
                        example: { "error" => { "code" => "rate_limit_exceeded", "message" => "Rate limit exceeded" } },
                        confidence: 0.95, evidence: ["http 429 -> rate_limit (errors.yml)"], source: "example" },
    "RequestMethods" => { discriminator_path: "recipient.type", values: %w[sbp card], default: "sbp", source: "enum",
                          confidence: 0.9 },
    "StatusMapping" => { provider: "completed", canonical: "approved", confidence: 0.95, source: "dictionary",
                         evidence: ["statuses.yml: completed -> approved"] },
    "Signature" => { location: "header", name: "X-NovaPay-Signature", algorithm: "hmac-sha256", encoding: "unknown",
                     message: "unknown", secret: "callback_secret", confidence: 0.9,
                     evidence: ["parameter: X-NovaPay-Signature (header)"], source: "parameter" },
    "WebhookEvent" => { value: "payout.completed", canonical_status: "approved", confidence: 0.95,
                        source: "dictionary" },
    "WebhookResponse" => { http: 200, example: { "received" => true } },
    "GatewayConfig" => { external_method: "sbp_payout", gateway: "RUB_SBP_WITHDRAW", direction: "withdraw",
                         currency: "RUB", method: "sbp", confidence: 0.9, evidence: ["currency: RUB (constant)"] },
    "OverrideApplied" => { key: "amount_unit", target: "CreatePayoutRequest.amount", value: "minor",
                           note: "from overrides.yml" }
  }.freeze
end
