# frozen_string_literal: true

# Generated by provider-integrator 0.1.0: RSpec for Provider::BearerpayService over fixtures.json
# through WebMock (no network).
# Run from this directory: rspec bearerpay_service_spec.rb (gems: rspec, webmock).
# base_contract.rb (Provider::BaseService, Provider::HttpClient) is a stub for local runs
# (docs/ASSUMPTIONS.md).

require 'json'
require 'rspec'
require 'webmock/rspec'
require_relative 'base_contract'
require_relative 'bearerpay_service'

RSpec.describe Provider::BearerpayService do
  let(:fixtures) { JSON.parse(File.read(File.join(__dir__, 'fixtures.json'))) }
  let(:credentials) { { token: 'test-token' } }
  let(:service) { described_class.new(client: Provider::HttpClient.new, credentials: credentials) }
  let(:requests) { [] }
  # The platform operation built from fixtures.json (the create request and its success response).
  let(:operation) do
    Provider::Operation.new(
      id: 'inv-2026-000841',
      amount: 2500,
      currency: 'USD',
      provider_operation_id: 'tr_9k2m4p7q1x3v5z8b',
      payout_requisite: {
        'ach' => {
          'name'           => 'Jane R. Miller',
          'account_number' => '000123456789',
          'bank_code'      => '021000021'
        }
      }
    )
  end

  # An example of fixtures.json without the generator markers (_synthetic, _synthetic_fields).
  def fixture(*keys)
    fixtures.dig(*keys).reject { |key, _| key.start_with?('_') }
  end

  # Stubs one provider response and records every request the service sends to url.
  def stub_provider(verb, url, status, body, headers: {})
    stub_request(verb, url).to_return do |request|
      requests << request
      { status: status, body: JSON.generate(body), headers: { 'Content-Type' => 'application/json' }.merge(headers) }
    end
  end

  # The body of the last request the service sent, as the provider reads it.
  def sent_body
    JSON.parse(requests.last.body)
  end

  # A copy of the operation with some members replaced.
  def operation_with(**changes)
    Provider::Operation.new(**operation.to_h, **changes)
  end

  describe '#create_request' do
    let(:url) { "#{described_class::BASE_URL}/transfers" }
    let(:request_headers) do
      { 'Authorization' => 'Bearer test-token', 'X-Request-Id' => 'inv-2026-000841' }
    end

    it 'POSTs the create request of fixtures.json with the auth headers' do
      stub_provider(:post, url, 201, fixture('create_request', 'response_201'))

      service.create_request(operation, 'ach')

      expect(a_request(:post, url).with(headers: request_headers)).to have_been_made.once
      expect(sent_body).to include(
        'amount'           => 250_000,
        'currency'         => 'USD',
        'reference'        => 'inv-2026-000841',
        'destination_type' => 'ach',
        'holder_name'      => 'Jane R. Miller',
        'account_number'   => '000123456789',
        'routing_number'   => '021000021'
      )
    end

    it 'returns success with the provider id and the mapped status of response_201' do
      stub_provider(:post, url, 201, fixture('create_request', 'response_201'))

      result = service.create_request(operation, 'ach')

      expect(result).to be_success
      expect(result.provider_operation_id).to eq('tr_9k2m4p7q1x3v5z8b')
      expect(result.status).to eq('in_progress')
    end

    it 'maps HTTP 400 to failure(:unprocessable_entity, provider.validation_error)' do
      stub_provider(:post, url, 400, fixture('create_request', 'response_400'))

      result = service.create_request(operation, 'ach')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'provider.validation_error'])
      expect(result.details[:provider_code]).to eq('VALIDATION_FAILED')
    end

    it 'maps HTTP 401 to failure(:unauthorized, provider.invalid_credentials)' do
      stub_provider(:post, url, 401, fixture('create_request', 'response_401'))

      result = service.create_request(operation, 'ach')

      expect([result.error, result.code]).to eq([:unauthorized, 'provider.invalid_credentials'])
      expect(result.details[:provider_code]).to eq('INVALID_TOKEN')
    end

    it 'maps HTTP 402 to failure(:provider_error, provider.insufficient_balance)' do
      stub_provider(:post, url, 402, fixture('create_request', 'response_402'))

      result = service.create_request(operation, 'ach')

      expect([result.error, result.code]).to eq([:provider_error, 'provider.insufficient_balance'])
      expect(result.details[:provider_code]).to eq('INSUFFICIENT_FUNDS')
    end

    it 'maps HTTP 403 to failure(:unauthorized, provider.invalid_credentials)' do
      stub_provider(:post, url, 403, fixture('create_request', 'response_403'))

      result = service.create_request(operation, 'ach')

      expect([result.error, result.code]).to eq([:unauthorized, 'provider.invalid_credentials'])
      expect(result.details[:provider_code]).to eq('ACCOUNT_BLOCKED')
    end

    it 'maps HTTP 409 to failure(:unprocessable_entity, provider.conflict)' do
      stub_provider(:post, url, 409, fixture('create_request', 'response_409'))

      result = service.create_request(operation, 'ach')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'provider.conflict'])
      expect(result.details[:provider_code]).to eq('DUPLICATE_REFERENCE')
    end

    it 'maps HTTP 422 to failure(:unprocessable_entity, provider.validation_error)' do
      stub_provider(:post, url, 422, fixture('create_request', 'response_422'))

      result = service.create_request(operation, 'ach')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'provider.validation_error'])
      expect(result.details[:provider_code]).to eq('AMOUNT_LIMIT_EXCEEDED')
    end

    it 'maps HTTP 429 to failure(:too_many_requests, provider.rate_limit) with Retry-After' do
      stub_provider(:post, url, 429, fixture('create_request', 'response_429'), headers: { 'Retry-After' => '60' })

      result = service.create_request(operation, 'ach')

      expect([result.error, result.code]).to eq([:too_many_requests, 'provider.rate_limit'])
      expect(result.details[:provider_code]).to eq('THROTTLED')
      expect(result.details[:retry_after]).to eq(60)
    end

    it 'maps HTTP 500 to failure(:provider_error, provider.internal_error)' do
      stub_provider(:post, url, 500, fixture('create_request', 'response_500'))

      result = service.create_request(operation, 'ach')

      expect([result.error, result.code]).to eq([:provider_error, 'provider.internal_error'])
      expect(result.details[:provider_code]).to eq('INTERNAL_ERROR')
    end

    it 'maps HTTP 503 to failure(:provider_error, provider.internal_error)' do
      stub_provider(:post, url, 503, fixture('create_request', 'response_503'))

      result = service.create_request(operation, 'ach')

      expect([result.error, result.code]).to eq([:provider_error, 'provider.internal_error'])
      expect(result.details[:provider_code]).to eq('PROVIDER_UNAVAILABLE')
      expect(result.details[:retry_after]).to eq(900)
    end

    it 'refuses an unknown request_method without calling the provider' do
      result = service.create_request(operation, 'unsupported')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'unsupported_request_method'])
      expect(WebMock).not_to have_requested(:any, /./)
    end
  end

  describe '#fetch_status' do
    let(:url) { "#{described_class::BASE_URL}/transfers/#{operation.provider_operation_id}" }

    it 'GETs the operation with the auth headers and maps the status of response_200' do
      stub_provider(:get, url, 200, fixture('fetch_status', 'response_200'))

      result = service.fetch_status(operation)

      expect(a_request(:get, url).with(headers: { 'Authorization' => 'Bearer test-token' })).to have_been_made.once
      expect(result).to be_success
      expect(result.status).to eq('approved')
    end

    it 'maps HTTP 401 to failure(:unauthorized, provider.invalid_credentials)' do
      stub_provider(:get, url, 401, fixture('fetch_status', 'response_401'))

      result = service.fetch_status(operation)

      expect([result.error, result.code]).to eq([:unauthorized, 'provider.invalid_credentials'])
      expect(result.details[:provider_code]).to eq('INVALID_TOKEN')
    end

    it 'maps HTTP 404 to failure(:provider_error, provider.not_found)' do
      stub_provider(:get, url, 404, fixture('fetch_status', 'response_404'))

      result = service.fetch_status(operation)

      expect([result.error, result.code]).to eq([:provider_error, 'provider.not_found'])
      expect(result.details[:provider_code]).to eq('TRANSFER_NOT_FOUND')
    end

    it 'maps HTTP 429 to failure(:too_many_requests, provider.rate_limit)' do
      stub_provider(:get, url, 429, fixture('fetch_status', 'response_429'), headers: { 'Retry-After' => '60' })

      result = service.fetch_status(operation)

      expect([result.error, result.code]).to eq([:too_many_requests, 'provider.rate_limit'])
      expect(result.details[:provider_code]).to eq('THROTTLED')
      expect(result.details[:retry_after]).to eq(60)
    end
  end

  describe '#process_callback' do
    it 'raises NotImplementedError: the spec declares no webhook (W304)' do
      expect { service.process_callback({}) }.to raise_error(NotImplementedError)
    end
  end

  describe '#check_conditions' do
    it 'accepts the operation built from fixtures.json' do
      expect(service.check_conditions(operation, 'ach')).to be_success
    end

    it 'refuses an amount below MIN_AMOUNT' do
      result = service.check_conditions(operation_with(amount: described_class::MIN_AMOUNT - 1), 'ach')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'amount_too_low'])
    end

    it 'refuses an amount above MAX_AMOUNT' do
      result = service.check_conditions(operation_with(amount: described_class::MAX_AMOUNT + 1), 'ach')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'amount_too_high'])
    end

    it 'refuses an operation without the requisites of REQUIRED_REQUISITES' do
      result = service.check_conditions(operation_with(payout_requisite: {}), 'ach')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'missing_requisite'])
    end

    it 'refuses a request_method outside REQUEST_METHODS' do
      result = service.check_conditions(operation, 'unsupported')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'unsupported_request_method'])
    end
  end
end
