# frozen_string_literal: true

# Generated by provider-integrator 0.1.0 from "BearerPay Transfers API" 2.4.0 (OpenAPI 3.0.3).
# Contract: Provider::BaseService (see INTEGRATION.md; base_contract.rb is a stub for local runs).
# Do not edit by hand: re-run the generator and pin corrections in overrides.yml.
# "Evidence:" comments cite the spec; "TODO(confidence ...)" marks what needs confirmation.

require 'uri'

class Provider
  class BearerpayService < BaseService
    # Sandbox by default; production: https://api.bearerpay.example/v2.
    BASE_URL = ENV.fetch('BEARERPAY_BASE_URL', 'https://sandbox.bearerpay.example/v2')

    # Payout methods accepted as request_method (enum of destination_type); the first is the default.
    REQUEST_METHODS = %w[ach wire card].freeze

    # minimum of amount: 10000 in minor units of the provider = 100 in major units of operation.amount.
    MIN_AMOUNT = 100

    # maximum of amount: 5000000 in minor units of the provider = 50000 in major units of
    # operation.amount.
    MAX_AMOUNT = 50_000

    # Canonical requisite names each payout method needs (required in the schema, or required when the
    # method matches - see INTEGRATION.md).
    REQUIRED_REQUISITES = {
      'ach'  => %w[name account_number bank_code],
      'wire' => %w[name],
      'card' => %w[name card_number]
    }.freeze

    # POST /transfers (createTransfer).
    def create_request(operation, request_method = 'ach')
      payload =
        case request_method
        when 'ach' then build_ach_payload(operation)
        when 'wire' then build_wire_payload(operation)
        when 'card' then build_card_payload(operation)
        end
      return failure(:unprocessable_entity, 'unsupported_request_method') if payload.nil?

      headers = auth_headers.merge(idempotency_headers(operation))
      response = client.post("#{BASE_URL}/transfers", json: payload, headers: headers)
      parse_create_response(operation, response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # GET /transfers/{transfer_id} (getTransferStatus).
    def fetch_status(operation)
      response = client.get("#{BASE_URL}/transfers/#{operation.provider_operation_id}", headers: auth_headers)
      parse_status_response(operation, response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # TODO(confidence 0.0): the spec declares no webhook (W304); poll fetch_status instead
    def process_callback(payload)
      raise NotImplementedError, 'process_callback: no webhook in the spec'
    end

    # Pre-checks before create_request; super runs the platform checks first.
    def check_conditions(operation, request_method)
      base_result = super
      return base_result if base_result.failed?

      unless REQUEST_METHODS.include?(request_method)
        return failure(:unprocessable_entity, 'unsupported_request_method')
      end
      # Evidence: description: в центах; error example (400): cents; minimum: 10000
      return failure(:unprocessable_entity, 'amount_too_low') if operation.amount < MIN_AMOUNT
      # Evidence: description: в центах; error example (400): cents; minimum: 10000
      return failure(:unprocessable_entity, 'amount_too_high') if operation.amount > MAX_AMOUNT

      missing = missing_requisites(operation, request_method)
      return failure(:unprocessable_entity, 'missing_requisite') unless missing.empty?

      success
    end

    # Outside the BaseService contract (kind list): GET /transfers (listTransfers).
    # История переводов
    def list_requests(params = {})
      url = "#{BASE_URL}/transfers"
      url = "#{url}?#{URI.encode_www_form(params)}" unless params.empty?
      response = client.get(url, headers: auth_headers)
      parse_list_requests_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # Outside the BaseService contract (kind unknown): POST /transfers/quote (quoteTransferFee).
    # Рассчитать комиссию перевода
    # TODO(confidence 0.0): operation kind unknown with confidence 0.0
    def quote_transfer_fee(operation, request_method)
      payload = build_quote_transfer_fee_payload(operation, request_method)
      url = "#{BASE_URL}/transfers/quote"
      response = client.post(url, json: payload, headers: auth_headers)
      parse_quote_transfer_fee_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # Outside the BaseService contract (kind cancel): POST /transfers/{transfer_id}/cancel
    # (cancelTransfer).
    # Отменить перевод
    def cancel_request(operation)
      url = "#{BASE_URL}/transfers/#{operation.provider_operation_id}/cancel"
      response = client.post(url, headers: auth_headers)
      parse_cancel_request_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # Outside the BaseService contract (kind status): GET /transfers/{transfer_id}/receipt
    # (downloadTransferReceipt).
    # Квитанция по переводу
    def download_transfer_receipt(operation)
      url = "#{BASE_URL}/transfers/#{operation.provider_operation_id}/receipt"
      response = client.get(url, headers: auth_headers)
      parse_download_transfer_receipt_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    private

    # Body of POST /transfers for request_method 'ach' (schema CreateTransferRequest).
    def build_ach_payload(operation)
      {
        # Evidence: description: в центах; error example (400): cents; minimum: 10000
        amount: amount_in_minor_units(operation.amount),
        currency: 'USD',
        reference: operation.id,
        destination_type: 'ach',
        holder_name: operation.payout_requisite.dig('ach', 'name'),
        # TODO(confidence 0.6): required when destination_type = ach (description: Обязателен, если
        # destination_type = ach)
        account_number: operation.payout_requisite.dig('ach', 'account_number'),
        # TODO(confidence 0.6): required when destination_type = ach (description: Обязателен, если
        # destination_type = ach)
        routing_number: operation.payout_requisite.dig('ach', 'bank_code'),
        # TODO(confidence 0.0): required field purpose_code has no platform source (W403)
        purpose_code: nil
      }.compact
    end

    # Body of POST /transfers for request_method 'wire' (schema CreateTransferRequest).
    def build_wire_payload(operation)
      {
        # Evidence: description: в центах; error example (400): cents; minimum: 10000
        amount: amount_in_minor_units(operation.amount),
        currency: 'USD',
        reference: operation.id,
        destination_type: 'wire',
        holder_name: operation.payout_requisite.dig('wire', 'name'),
        # TODO(confidence 0.0): required field purpose_code has no platform source (W403)
        purpose_code: nil
      }.compact
    end

    # Body of POST /transfers for request_method 'card' (schema CreateTransferRequest).
    def build_card_payload(operation)
      {
        # Evidence: description: в центах; error example (400): cents; minimum: 10000
        amount: amount_in_minor_units(operation.amount),
        currency: 'USD',
        reference: operation.id,
        destination_type: 'card',
        holder_name: operation.payout_requisite.dig('card', 'name'),
        # TODO(confidence 0.6): required when destination_type = card (description: Required for
        # destination_type = card)
        card_number: operation.payout_requisite.dig('card', 'card_number'),
        # TODO(confidence 0.0): required field purpose_code has no platform source (W403)
        purpose_code: nil
      }.compact
    end

    # Success statuses 201; everything else goes through ERROR_MAP.
    def parse_create_response(operation, response)
      body = response.body || {}
      case response.status
      when 201 then success(provider_operation_id: body['transfer_id'], status: map_status(body['status']),
                            response: body)
      else provider_error(response)
      end
    end

    def parse_status_response(operation, response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(status: map_status(body['status']), response: body)
    end

    # Canonical requisite names the payout method needs (REQUIRED_REQUISITES) that are missing from
    # operation.payout_requisite[request_method].
    def missing_requisites(operation, request_method)
      requisite = operation.payout_requisite.to_h[request_method] || {}
      REQUIRED_REQUISITES.fetch(request_method, []).reject { |field| requisite[field] }
    end

    def parse_list_requests_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(response: body)
    end

    # Body of POST /transfers/quote.
    def build_quote_transfer_fee_payload(operation, request_method = nil)
      {
        # Evidence: description: в центах; error example (400): cents; minimum: 10000
        # Units assumed equal to create_request (not analysed for this operation)
        amount: amount_in_minor_units(operation.amount),
        currency: 'USD',
        destination_type: request_method
      }.compact
    end

    def parse_quote_transfer_fee_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(response: body)
    end

    def parse_cancel_request_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(status: map_status(body['status']), response: body)
    end

    def parse_download_transfer_receipt_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(response: body)
    end

    # BearerAuth: http_bearer in header Authorization. Evidence: securitySchemes.BearerAuth: http bearer
    # in header Authorization; security: BearerAuth used by 6 of 6 operations
    def auth_headers
      { 'Authorization' => "Bearer #{credentials[:token]}" }
    end

    # X-Request-Id (format uuid): operation.id is the stable key of the request; the provider answers a
    # repeat with the original result.
    def idempotency_headers(operation)
      { 'X-Request-Id' => operation.id.to_s }
    end

    # Provider status -> Space Payments status (STATUS_MAP); unknown values stay in_progress until the
    # next notification.
    def map_status(value)
      STATUS_MAP.fetch(value.to_s, 'in_progress')
    end

    # Error response -> failure through ERROR_MAP (HTTP status -> canonical code).
    def provider_error(response)
      body = response.body || {}
      details = { provider_code: error_code(body), retry_after: retry_after_seconds(response) }.compact
      case ERROR_MAP.fetch(response.status) { response.status >= 500 ? 'internal_error' : 'validation_error' }
      when 'invalid_credentials' then failure(:unauthorized, 'provider.invalid_credentials', **details)
      when 'insufficient_balance' then failure(:provider_error, 'provider.insufficient_balance', **details)
      when 'rate_limit' then failure(:too_many_requests, 'provider.rate_limit', **details)
      when 'internal_error' then failure(:provider_error, 'provider.internal_error', **details)
      when 'not_found' then failure(:provider_error, 'provider.not_found', **details)
      when 'conflict' then failure(:unprocessable_entity, 'provider.conflict', **details)
      else failure(:unprocessable_entity, 'provider.validation_error', **details)
      end
    end

    # Retry-After of a rate-limited response in seconds (body or header); nil when the provider sent none.
    def retry_after_seconds(response)
      header = response.headers.to_h.find { |name, _| name.to_s.casecmp?('Retry-After') }&.last
      body_value = (response.body || {})['retry_after_seconds']
      (header || body_value)&.to_i
    end

    # Provider error code of an error response (error_code in the spec).
    def error_code(body)
      body['error_code']&.to_s
    end

    # operation.amount is in major units; the provider expects minor units (x 100).
    # round (not to_i) keeps 10.15 * 100 from truncating to 1014 with Float amounts.
    def amount_in_minor_units(amount)
      (amount * 100).round
    end

    # Provider status -> Space Payments status (statuses.yml); evidence per status in INTEGRATION.md.
    STATUS_MAP = {
      'NEW'      => 'in_progress',
      'SENT'     => 'in_progress',
      'DONE'     => 'approved',
      'DECLINED' => 'rejected'
    }.freeze

    # HTTP status -> canonical error code (Space Payments); provider codes and evidence in INTEGRATION.md.
    ERROR_MAP = {
      400 => 'validation_error',
      401 => 'invalid_credentials',
      402 => 'insufficient_balance',
      403 => 'invalid_credentials',
      404 => 'not_found',
      409 => 'conflict',
      422 => 'validation_error',
      429 => 'rate_limit',
      500 => 'internal_error',
      503 => 'internal_error'
    }.freeze

    # HTTP status -> what the platform should do (canonical_contract.yml -> actions).
    ERROR_ACTIONS = {
      400 => 'terminal_reject',
      401 => 'fatal_block_provider',
      402 => 'retry_later',
      403 => 'fatal_block_provider',
      404 => 'unknown_state',
      409 => 'conflict',
      422 => 'terminal_reject',
      429 => 'retry_with_backoff',
      500 => 'retry_alert_ops',
      503 => 'retry_later'
    }.freeze
  end
end
