# frozen_string_literal: true

# Generated by provider-integrator 0.1.0: RSpec for Provider::RublepayService over fixtures.json
# through WebMock (no network).
# Run from this directory: rspec rublepay_service_spec.rb (gems: rspec, webmock).
# base_contract.rb (Provider::BaseService, Provider::HttpClient) is a stub for local runs
# (docs/ASSUMPTIONS.md).

require 'json'
require 'openssl'
require 'rspec'
require 'webmock/rspec'
require_relative 'base_contract'
require_relative 'rublepay_service'

RSpec.describe Provider::RublepayService do
  let(:fixtures) { JSON.parse(File.read(File.join(__dir__, 'fixtures.json'))) }
  let(:credentials) do
    { api_key: 'test-api_key', callback_secret: 'test-callback_secret', merchant_id: 'shop_10245' }
  end
  let(:service) { described_class.new(client: Provider::HttpClient.new, credentials: credentials) }
  let(:requests) { [] }
  let(:auth_query) { { 'api_key' => credentials[:api_key] } }
  # The platform operation built from fixtures.json (the create request and its success response).
  let(:operation) do
    Provider::Operation.new(
      id: 'ord-2026-000871',
      amount: 1500,
      currency: 'RUB',
      provider_operation_id: 'dp_8c41f0e2',
      payout_requisite: {
        'card' => {
          'card_number'  => '4111111111111111',
          'expiry_month' => '07',
          'expiry_year'  => '29',
          'cvc'          => '123',
          'name'         => 'IVAN PETROV'
        }
      }
    )
  end

  # An example of fixtures.json without the generator markers (_synthetic, _synthetic_fields).
  def fixture(*keys)
    fixtures.dig(*keys).reject { |key, _| key.start_with?('_') }
  end

  # Stubs one provider response and records every request the service sends to url.
  def stub_provider(verb, url, status, body, headers: {})
    stub_request(verb, url).with(query: auth_query).to_return do |request|
      requests << request
      { status: status, body: JSON.generate(body), headers: { 'Content-Type' => 'application/json' }.merge(headers) }
    end
  end

  # The body of the last request the service sent, as the provider reads it.
  def sent_body
    JSON.parse(requests.last.body)
  end

  # A copy of the operation with some members replaced.
  def operation_with(**changes)
    Provider::Operation.new(**operation.to_h, **changes)
  end

  # Signs a notification body the way verify_signature! checks it (HMAC-SHA512, hex).
  def signature_for(body)
    message = JSON.generate(body)
    OpenSSL::HMAC.hexdigest('SHA512', credentials[:callback_secret], message)
  end

  # The payload process_callback receives for a signed notification.
  def signed_payload(body)
    {
      'body'     => body,
      'raw_body' => JSON.generate(body),
      'headers'  => { 'X-RublePay-Sign' => signature_for(body) }
    }
  end

  describe '#create_request' do
    let(:url) { "#{described_class::BASE_URL}/deposits" }
    let(:request_headers) { { 'X-Request-Id' => 'ord-2026-000871' } }

    it 'POSTs the create request of fixtures.json with the auth headers' do
      stub_provider(:post, url, 201, fixture('create_request', 'response_201'))

      service.create_request(operation, 'card')

      expect(a_request(:post, url).with(query: auth_query, headers: request_headers)).to have_been_made.once
      expect(sent_body).to include(
        'merchant_order_id' => 'ord-2026-000871',
        'merchant_id'       => 'shop_10245',
        'amount'            => '1500.00',
        'currency'          => 'RUB'
      )
      expect(sent_body['payment_details']).to include(
        'source_type'     => 'card',
        'pan'             => '4111111111111111',
        'expiry_month'    => '07',
        'expiry_year'     => '29',
        'cvc'             => '123',
        'cardholder_name' => 'IVAN PETROV'
      )
    end

    it 'returns success with the provider id and the mapped status of response_201' do
      stub_provider(:post, url, 201, fixture('create_request', 'response_201'))

      result = service.create_request(operation, 'card')

      expect(result).to be_success
      expect(result.provider_operation_id).to eq('dp_8c41f0e2')
      expect(result.status).to eq('in_progress')
    end

    it 'maps HTTP 400 to failure(:unprocessable_entity, provider.validation_error)' do
      stub_provider(:post, url, 400, fixture('create_request', 'response_400'))

      result = service.create_request(operation, 'card')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'provider.validation_error'])
      expect(result.details[:provider_code]).to eq('malformed_request')
    end

    it 'maps HTTP 401 to failure(:unauthorized, provider.invalid_credentials)' do
      stub_provider(:post, url, 401, fixture('create_request', 'response_401'))

      result = service.create_request(operation, 'card')

      expect([result.error, result.code]).to eq([:unauthorized, 'provider.invalid_credentials'])
      expect(result.details[:provider_code]).to eq('merchant_disabled')
    end

    it 'maps HTTP 409 to failure(:unprocessable_entity, provider.conflict)' do
      stub_provider(:post, url, 409, fixture('create_request', 'response_409'))

      result = service.create_request(operation, 'card')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'provider.conflict'])
      expect(result.details[:provider_code]).to eq('deposit_already_registered')
    end

    it 'maps HTTP 422 to failure(:unprocessable_entity, provider.validation_error)' do
      stub_provider(:post, url, 422, fixture('create_request', 'response_422'))

      result = service.create_request(operation, 'card')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'provider.validation_error'])
      expect(result.details[:provider_code]).to eq('amount_less_than_min')
    end

    it 'maps HTTP 429 to failure(:too_many_requests, provider.rate_limit)' do
      stub_provider(:post, url, 429, fixture('create_request', 'response_429'))

      result = service.create_request(operation, 'card')

      expect([result.error, result.code]).to eq([:too_many_requests, 'provider.rate_limit'])
      expect(result.details[:provider_code]).to eq('too_many_requests')
      expect(result.details[:retry_after]).to eq(30)
    end

    it 'maps HTTP 503 to failure(:provider_error, provider.internal_error)' do
      stub_provider(:post, url, 503, fixture('create_request', 'response_503'))

      result = service.create_request(operation, 'card')

      expect([result.error, result.code]).to eq([:provider_error, 'provider.internal_error'])
      expect(result.details[:provider_code]).to eq('acquirer_unavailable')
    end

    it 'refuses an unknown request_method without calling the provider' do
      result = service.create_request(operation, 'unsupported')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'unsupported_request_method'])
      expect(WebMock).not_to have_requested(:any, /./)
    end
  end

  describe '#fetch_status' do
    let(:url) { "#{described_class::BASE_URL}/deposits/#{operation.provider_operation_id}" }

    it 'GETs the operation with the auth headers and maps the status of response_200' do
      stub_provider(:get, url, 200, fixture('fetch_status', 'response_200'))

      result = service.fetch_status(operation)

      expect(a_request(:get, url).with(query: auth_query)).to have_been_made.once
      expect(result).to be_success
      expect(result.status).to eq('approved')
    end

    it 'maps HTTP 401 to failure(:unauthorized, provider.invalid_credentials)' do
      stub_provider(:get, url, 401, fixture('fetch_status', 'response_401'))

      result = service.fetch_status(operation)

      expect([result.error, result.code]).to eq([:unauthorized, 'provider.invalid_credentials'])
      expect(result.details[:provider_code]).to eq('merchant_disabled')
    end

    it 'maps HTTP 404 to failure(:provider_error, provider.not_found)' do
      stub_provider(:get, url, 404, fixture('fetch_status', 'response_404'))

      result = service.fetch_status(operation)

      expect([result.error, result.code]).to eq([:provider_error, 'provider.not_found'])
      expect(result.details[:provider_code]).to eq('deposit_not_found')
    end

    it 'maps HTTP 429 to failure(:too_many_requests, provider.rate_limit)' do
      stub_provider(:get, url, 429, fixture('fetch_status', 'response_429'))

      result = service.fetch_status(operation)

      expect([result.error, result.code]).to eq([:too_many_requests, 'provider.rate_limit'])
      expect(result.details[:provider_code]).to eq('too_many_requests')
      expect(result.details[:retry_after]).to eq(30)
    end
  end

  describe '#process_callback' do
    it 'approves the operation for the callback fixture (event deposit.succeeded)' do
      result = service.process_callback(signed_payload(fixture('callback', 'payload')))

      expect(result).to be_success
      expect(result.status).to eq('approved')
      expect(result.provider_operation_id).to eq('dp_8c41f0e2')
    end

    it 'rejects the operation for the callback_failed fixture (event deposit.expired)' do
      result = service.process_callback(signed_payload(fixture('callback_failed', 'payload')))

      expect(result).to be_success
      expect(result.status).to eq('rejected')
      expect(result.provider_operation_id).to eq('dp_9d5210ff')
      expect(result.details[:error_code]).to eq('payment_window_closed')
    end

    it 'refuses a payload whose signature does not verify' do
      payload = signed_payload(fixture('callback', 'payload'))
      payload['headers']['X-RublePay-Sign'] = 'invalid'

      result = service.process_callback(payload)

      expect([result.error, result.code]).to eq([:unauthorized, 'invalid_signature'])
    end
  end

  describe '#check_conditions' do
    it 'accepts the operation built from fixtures.json' do
      expect(service.check_conditions(operation, 'card')).to be_success
    end

    it 'refuses an operation without the requisites of REQUIRED_REQUISITES' do
      result = service.check_conditions(operation_with(payout_requisite: {}), 'card')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'missing_requisite'])
    end

    it 'refuses a request_method outside REQUEST_METHODS' do
      result = service.check_conditions(operation, 'unsupported')

      expect([result.error, result.code]).to eq([:unprocessable_entity, 'unsupported_request_method'])
    end
  end
end
