# frozen_string_literal: true

# Generated by provider-integrator 0.1.0 from "RublePay Deposit API" 2.4.1 (OpenAPI 3.0.3).
# Contract: Provider::BaseService (see INTEGRATION.md; base_contract.rb is a stub for local runs).
# Do not edit by hand: re-run the generator and pin corrections in overrides.yml.
# "Evidence:" comments cite the spec; "TODO(confidence ...)" marks what needs confirmation.

require 'json'
require 'openssl'
require 'uri'

class Provider
  class RublepayService < BaseService
    # Sandbox by default; production: https://api.rublepay.example/v2.
    BASE_URL = ENV.fetch('RUBLEPAY_BASE_URL', 'https://api.sandbox.rublepay.example/v2')

    # Sent in the request body as redirect_url; configure per environment.
    REDIRECT_URL = ENV.fetch('RUBLEPAY_REDIRECT_URL', nil)

    # Sent in the request body as callback_url; configure per environment.
    CALLBACK_URL = ENV.fetch('RUBLEPAY_CALLBACK_URL', nil)

    # Payout methods accepted as request_method (discriminator of payment_details.source_type); the first
    # is the default.
    REQUEST_METHODS = %w[card sbp account].freeze

    # Canonical requisite names each payout method needs (required in the schema, or required when the
    # method matches - see INTEGRATION.md).
    REQUIRED_REQUISITES = {
      'card'    => %w[card_number expiry_month expiry_year cvc],
      'sbp'     => %w[bank_code],
      'account' => %w[account_number bank_code inn]
    }.freeze

    # POST /deposits (initDeposit).
    def create_request(operation, request_method = 'card')
      payload =
        case request_method
        when 'card' then build_card_payload(operation)
        when 'sbp' then build_sbp_payload(operation)
        when 'account' then build_account_payload(operation)
        end
      return failure(:unprocessable_entity, 'unsupported_request_method') if payload.nil?

      headers = auth_headers.merge(idempotency_headers(operation))
      response = client.post(with_api_key("#{BASE_URL}/deposits"), json: payload, headers: headers)
      parse_create_response(operation, response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # GET /deposits/{deposit_id} (getDepositState).
    def fetch_status(operation)
      response = client.get(with_api_key("#{BASE_URL}/deposits/#{operation.provider_operation_id}"),
                            headers: auth_headers)
      parse_status_response(operation, response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # POST /notifications/deposit (depositNotification); source: path_heuristic.
    # payload is the parsed JSON body, or { 'body' => body, 'headers' => headers, 'raw_body' => raw body }
    # (INTEGRATION.md, Webhook).
    def process_callback(payload)
      verify_signature!(payload) # HMAC-SHA512 from X-RublePay-Sign
      body = callback_body(payload)
      case body['event']
      when 'deposit.awaiting_payment' then success(status: 'in_progress', response: body)
      when 'deposit.partially_paid', 'deposit.succeeded' then approve_operation(body['deposit_id'])
      when 'deposit.refunded', 'deposit.expired' then reject_operation(body['deposit_id'], body['error_code'])
      else failure(:unprocessable_entity, 'unknown_event')
      end
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'invalid_signature')
    end

    # Pre-checks before create_request; super runs the platform checks first.
    def check_conditions(operation, request_method)
      base_result = super
      return base_result if base_result.failed?

      unless REQUEST_METHODS.include?(request_method)
        return failure(:unprocessable_entity, 'unsupported_request_method')
      end

      missing = missing_requisites(operation, request_method)
      return failure(:unprocessable_entity, 'missing_requisite') unless missing.empty?

      success
    end

    # Outside the BaseService contract (kind refund): POST /deposits/{deposit_id}/refunds (refundDeposit).
    # Оформить возврат по депозиту
    def refund_request(operation)
      payload = build_refund_request_payload(operation)
      url = with_api_key("#{BASE_URL}/deposits/#{operation.provider_operation_id}/refunds")
      response = client.post(url, json: payload, headers: auth_headers.merge(idempotency_headers(operation)))
      parse_refund_request_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # Outside the BaseService contract (kind unknown): POST /fees/quote (calculateDepositFee).
    # Рассчитать комиссию по будущему депозиту
    # TODO(confidence 0.0): operation kind unknown with confidence 0.0
    def calculate_deposit_fee(operation)
      payload = build_calculate_deposit_fee_payload(operation)
      url = with_api_key("#{BASE_URL}/fees/quote")
      response = client.post(url, json: payload, headers: auth_headers)
      parse_calculate_deposit_fee_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # Outside the BaseService contract (kind list): GET /directories/sbp-banks (listSbpBanks).
    # Список банков — участников СБП
    def list_requests(params = {})
      url = with_api_key("#{BASE_URL}/directories/sbp-banks")
      url = "#{url}?#{URI.encode_www_form(params)}" unless params.empty?
      response = client.get(url, headers: auth_headers)
      parse_list_requests_response(response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    private

    # Body of POST /deposits for request_method 'card' (schema CreateDepositRequest).
    def build_card_payload(operation)
      {
        merchant_order_id: operation.id,
        merchant_id: credentials[:merchant_id],
        # Evidence: description: рублях; pattern: ^\d+\.\d{2}$; type: string
        amount: amount_as_decimal_string(operation.amount),
        currency: 'RUB',
        payment_details: {
          source_type: 'card',
          # required when payment_details.source_type = card (discriminator payment_details.source_type = card)
          pan: operation.payout_requisite.dig('card', 'card_number'),
          # required when payment_details.source_type = card (discriminator payment_details.source_type = card)
          expiry_month: operation.payout_requisite.dig('card', 'expiry_month'),
          # required when payment_details.source_type = card (discriminator payment_details.source_type = card)
          expiry_year: operation.payout_requisite.dig('card', 'expiry_year'),
          # required when payment_details.source_type = card (discriminator payment_details.source_type = card)
          cvc: operation.payout_requisite.dig('card', 'cvc'),
          cardholder_name: operation.payout_requisite.dig('card', 'name')
        }.compact,
        return_url: REDIRECT_URL,
        notify_url: CALLBACK_URL
      }.compact
    end

    # Body of POST /deposits for request_method 'sbp' (schema CreateDepositRequest).
    def build_sbp_payload(operation)
      {
        merchant_order_id: operation.id,
        merchant_id: credentials[:merchant_id],
        # Evidence: description: рублях; pattern: ^\d+\.\d{2}$; type: string
        amount: amount_as_decimal_string(operation.amount),
        currency: 'RUB',
        payment_details: {
          source_type: 'sbp',
          # required when payment_details.source_type = sbp (discriminator payment_details.source_type = sbp)
          bank_member_id: operation.payout_requisite.dig('sbp', 'bank_code'),
          payer_phone: operation.payout_requisite.dig('sbp', 'payer_phone'),
          qr_type: operation.payout_requisite.dig('sbp', 'qr_type')
        }.compact,
        return_url: REDIRECT_URL,
        notify_url: CALLBACK_URL
      }.compact
    end

    # Body of POST /deposits for request_method 'account' (schema CreateDepositRequest).
    def build_account_payload(operation)
      {
        merchant_order_id: operation.id,
        merchant_id: credentials[:merchant_id],
        # Evidence: description: рублях; pattern: ^\d+\.\d{2}$; type: string
        amount: amount_as_decimal_string(operation.amount),
        currency: 'RUB',
        payment_details: {
          source_type: 'account',
          # required when payment_details.source_type = account (discriminator payment_details.source_type =
          # account)
          account_number: operation.payout_requisite.dig('account', 'account_number'),
          # required when payment_details.source_type = account (discriminator payment_details.source_type =
          # account)
          bank_bik: operation.payout_requisite.dig('account', 'bank_code'),
          # required when payment_details.source_type = account (discriminator payment_details.source_type =
          # account)
          inn: operation.payout_requisite.dig('account', 'inn'),
          payer_name: operation.payout_requisite.dig('account', 'payer_name')
        }.compact,
        return_url: REDIRECT_URL,
        notify_url: CALLBACK_URL
      }.compact
    end

    # Success statuses 201; everything else goes through ERROR_MAP.
    def parse_create_response(operation, response)
      body = response.body || {}
      case response.status
      when 201 then success(provider_operation_id: body['deposit_id'], status: map_status(body['state']),
                            response: body)
      else provider_error(response)
      end
    end

    def parse_status_response(operation, response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(status: map_status(body['state']), response: body)
    end

    # The parsed notification: payload['body'] under the platform envelope, else the payload itself.
    def callback_body(payload)
      payload['body'] || payload
    end

    # HMAC-SHA512 over the raw request body, hex, compared in constant time.
    # Evidence: operation description: Подпись передаётся в заголовке X-RublePay-Sign: HMAC-SHA512 от
    # сырого тела запроса, hex
    def verify_signature!(payload)
      signature = payload.dig('headers', 'X-RublePay-Sign').to_s
      message = payload['raw_body'] || JSON.generate(callback_body(payload))
      expected = OpenSSL::HMAC.hexdigest('SHA512', credentials[:callback_secret].to_s, message)
      return if !signature.empty? && secure_compare(expected, signature)

      raise Provider::UnauthorizedError, 'invalid_signature'
    end

    def secure_compare(left, right)
      left.bytesize == right.bytesize && OpenSSL.fixed_length_secure_compare(left, right)
    end

    # Canonical requisite names the payout method needs (REQUIRED_REQUISITES) that are missing from
    # operation.payout_requisite[request_method].
    def missing_requisites(operation, request_method)
      requisite = operation.payout_requisite.to_h[request_method] || {}
      REQUIRED_REQUISITES.fetch(request_method, []).reject { |field| requisite[field] }
    end

    # Body of POST /deposits/{deposit_id}/refunds.
    def build_refund_request_payload(operation, request_method = nil)
      {
        # Evidence: description: рублях; pattern: ^\d+\.\d{2}$; type: string
        # Units assumed equal to create_request (not analysed for this operation)
        amount: amount_as_decimal_string(operation.amount)
      }.compact
    end

    def parse_refund_request_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(status: map_status(body['state']), response: body)
    end

    # Body of POST /fees/quote.
    def build_calculate_deposit_fee_payload(operation, request_method = nil)
      {
        # Evidence: description: рублях; pattern: ^\d+\.\d{2}$; type: string
        # Units assumed equal to create_request (not analysed for this operation)
        amount: amount_as_decimal_string(operation.amount),
        currency: 'RUB',
        # TODO(confidence 0.0): required field source_type has no platform source (W403)
        source_type: nil
      }.compact
    end

    def parse_calculate_deposit_fee_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(response: body)
    end

    def parse_list_requests_response(response)
      body = response.body || {}
      return provider_error(response) unless response.status == 200

      success(response: body)
    end

    # MerchantKey: api_key in query api_key. Evidence: securitySchemes.MerchantKey: apiKey in query
    # api_key; security: MerchantKey used by 5 of 6 operations
    def auth_headers
      {}
    end

    # MerchantKey: the key travels as the query parameter api_key.
    def with_api_key(url)
      "#{url}#{url.include?('?') ? '&' : '?'}#{URI.encode_www_form('api_key' => credentials[:api_key])}"
    end

    # X-Request-Id (format uuid): operation.id is the stable key of the request; the provider answers a
    # repeat with the original result.
    def idempotency_headers(operation)
      { 'X-Request-Id' => operation.id.to_s }
    end

    # Provider status -> Space Payments status (STATUS_MAP); unknown values stay in_progress until the
    # next notification.
    def map_status(value)
      STATUS_MAP.fetch(value.to_s, 'in_progress')
    end

    # Error response -> failure through ERROR_MAP (HTTP status -> canonical code).
    def provider_error(response)
      body = response.body || {}
      details = { provider_code: error_code(body), retry_after: retry_after_seconds(response) }.compact
      case ERROR_MAP.fetch(response.status) { response.status >= 500 ? 'internal_error' : 'validation_error' }
      when 'invalid_credentials' then failure(:unauthorized, 'provider.invalid_credentials', **details)
      when 'rate_limit' then failure(:too_many_requests, 'provider.rate_limit', **details)
      when 'internal_error' then failure(:provider_error, 'provider.internal_error', **details)
      when 'not_found' then failure(:provider_error, 'provider.not_found', **details)
      when 'conflict' then failure(:unprocessable_entity, 'provider.conflict', **details)
      else failure(:unprocessable_entity, 'provider.validation_error', **details)
      end
    end

    # Retry-After of a rate-limited response in seconds (body); nil when the provider sent none.
    def retry_after_seconds(response)
      body_value = (response.body || {})['retry_in']
      body_value&.to_i
    end

    # Provider error code of an error response (error_code in the spec).
    def error_code(body)
      body['error_code']&.to_s
    end

    # The provider expects the amount as a decimal string with 2 places.
    def amount_as_decimal_string(amount)
      format('%.2f', amount)
    end

    # Provider status -> Space Payments status (statuses.yml); evidence per status in INTEGRATION.md.
    STATUS_MAP = {
      'created'          => 'in_progress',
      'awaiting_payment' => 'in_progress',
      'succeeded'        => 'approved',
      'partially_paid'   => 'in_progress',
      'refunded'         => 'rejected',
      'expired'          => 'rejected',
      'rejected'         => 'rejected'
    }.freeze

    # HTTP status -> canonical error code (Space Payments); provider codes and evidence in INTEGRATION.md.
    ERROR_MAP = {
      400 => 'validation_error',
      401 => 'invalid_credentials',
      404 => 'not_found',
      409 => 'conflict',
      422 => 'validation_error',
      429 => 'rate_limit',
      503 => 'internal_error'
    }.freeze

    # HTTP status -> what the platform should do (canonical_contract.yml -> actions).
    ERROR_ACTIONS = {
      400 => 'terminal_reject',
      401 => 'fatal_block_provider',
      404 => 'unknown_state',
      409 => 'conflict',
      422 => 'terminal_reject',
      429 => 'retry_with_backoff',
      503 => 'retry_later'
    }.freeze
  end
end
